import React from 'react';
import { Badge } from '@/components/ui/badge';
import { Sparkles, Building, Brain, Zap } from 'lucide-react';

export type ContentSource = 'ai-generated' | 'company-data' | 'auto-populated' | 'manual' | 'enhanced';

interface EnhancedContentIndicatorProps {
  source: ContentSource;
  confidence?: number;
  className?: string;
  showIcon?: boolean;
}

export function EnhancedContentIndicator({ 
  source, 
  confidence, 
  className = "", 
  showIcon = true 
}: EnhancedContentIndicatorProps) {
  const getSourceInfo = (source: ContentSource) => {
    switch (source) {
      case 'ai-generated':
        return {
          icon: <Brain className="w-3 h-3" />,
          label: 'AI Generated',
          variant: 'default' as const,
          description: 'Content generated by AI based on company context and regulatory requirements',
          bgColor: 'bg-blue-100 text-blue-800 border-blue-200'
        };
      case 'company-data':
        return {
          icon: <Building className="w-3 h-3" />,
          label: 'Company Data',
          variant: 'secondary' as const,
          description: 'Auto-populated from company settings and configuration',
          bgColor: 'bg-green-100 text-green-800 border-green-200'
        };
      case 'auto-populated':
        return {
          icon: <Zap className="w-3 h-3" />,
          label: 'Auto-filled',
          variant: 'outline' as const,
          description: 'Automatically filled from available data sources',
          bgColor: 'bg-yellow-100 text-yellow-800 border-yellow-200'
        };
      case 'enhanced':
        return {
          icon: <Sparkles className="w-3 h-3" />,
          label: 'Enhanced',
          variant: 'default' as const,
          description: 'Content enhanced through AI recommendations',
          bgColor: 'bg-purple-100 text-purple-800 border-purple-200'
        };
      case 'manual':
      default:
        return {
          icon: null,
          label: 'Manual Entry',
          variant: 'outline' as const,
          description: 'Manually entered content',
          bgColor: 'bg-gray-100 text-gray-800 border-gray-200'
        };
    }
  };

  const sourceInfo = getSourceInfo(source);

  return (
    <Badge 
      variant={sourceInfo.variant} 
      className={`text-xs flex items-center gap-1 ${sourceInfo.bgColor} ${className}`}
      title={sourceInfo.description}
    >
      {showIcon && sourceInfo.icon}
      {sourceInfo.label}
      {confidence && (
        <span className="ml-1 text-xs opacity-75">
          {Math.round(confidence * 100)}%
        </span>
      )}
    </Badge>
  );
}

/**
 * Enhanced highlighting utility for different content types
 */
export function getContentHighlighting(source: ContentSource): string {
  switch (source) {
    case 'ai-generated':
      return 'bg-blue-50 border-l-4 border-blue-300 pl-3';
    case 'company-data':
      return 'bg-green-50 border-l-4 border-green-300 pl-3';
    case 'auto-populated':
      return 'bg-yellow-50 border-l-4 border-yellow-300 pl-3';
    case 'enhanced':
      return 'bg-purple-50 border-l-4 border-purple-300 pl-3';
    case 'manual':
    default:
      return '';
  }
}