import type { GanttTask, GanttLink } from '@/types/ganttChart';

const d = (y: number, m: number, day: number): Date => new Date(y, m - 1, day);

export const SAMPLE_TASKS: GanttTask[] = [
    // ─── PHASE 0: DISCOVERY (2025) ─────────────────────────────────────────
    {
        id: 'p0',
        text: 'Discovery & Concept',
        type: 'category',
        start: d(2025, 7, 1),
        end: d(2025, 12, 31),
        progress: 100,
        progressStatus: 'completed',
    },
    {
        id: 't0a',
        text: 'Market Research',
        type: 'task',
        parent: 'p0',
        start: d(2025, 7, 1),
        end: d(2025, 9, 15),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'B. Sterling',
    },
    {
        id: 't0b',
        text: 'Concept Definition',
        type: 'task',
        parent: 'p0',
        start: d(2025, 9, 16),
        end: d(2025, 11, 30),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'B. Sterling',
    },
    {
        id: 't0c',
        text: 'Feasibility Study',
        type: 'task',
        parent: 'p0',
        start: d(2025, 10, 15),
        end: d(2025, 12, 20),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'L. Becker',
    },

    // ─── PHASE 1: DESIGN ───────────────────────────────────────────────────
    {
        id: 'p1',
        text: 'Design Phase',
        type: 'category',
        start: d(2026, 1, 5),
        end: d(2026, 3, 1),
        progress: 100,
        progressStatus: 'completed',
    },
    {
        id: 't1',
        text: 'Requirements Gathering',
        type: 'task',
        parent: 'p1',
        start: d(2026, 1, 5),
        end: d(2026, 1, 30),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'A. Sharma',
    },
    {
        id: 't1b',
        text: 'Stakeholder Workshops',
        type: 'task',
        parent: 'p1',
        start: d(2026, 1, 12),
        end: d(2026, 1, 26),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'A. Sharma',
    },
    {
        id: 't2',
        text: 'Architecture Review',
        type: 'task',
        parent: 'p1',
        start: d(2026, 2, 2),
        end: d(2026, 3, 1),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'R. Patel',
    },
    {
        id: 't2b',
        text: 'Risk Assessment (ISO 14971)',
        type: 'task',
        parent: 'p1',
        start: d(2026, 2, 9),
        end: d(2026, 3, 1),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'L. Becker',
    },
    {
        id: 't2c',
        text: 'Usability Engineering Plan',
        type: 'task',
        parent: 'p1',
        start: d(2026, 2, 16),
        end: d(2026, 2, 28),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'N. Wong',
    },

    // ─── PHASE 2: DEVELOPMENT ──────────────────────────────────────────────
    {
        id: 'p2',
        text: 'Development Phase',
        type: 'category',
        start: d(2026, 3, 2),
        end: d(2026, 6, 15),
        progress: 65,
        progressStatus: 'in-progress',
    },
    {
        id: 't3',
        text: 'Prototype Build',
        type: 'task',
        parent: 'p2',
        start: d(2026, 3, 2),
        end: d(2026, 4, 20),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'M. Iyer',
    },
    {
        id: 't3b',
        text: 'PCB Design & Fabrication',
        type: 'task',
        parent: 'p2',
        start: d(2026, 3, 9),
        end: d(2026, 4, 10),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'M. Iyer',
    },
    {
        id: 't4',
        text: 'Firmware Implementation',
        type: 'task',
        parent: 'p2',
        start: d(2026, 4, 13),
        end: d(2026, 6, 15),
        progress: 55,
        progressStatus: 'in-progress',
        assigned: 'D. Khan',
    },
    // ── Nested under t4: depth-2 + depth-3 sub-tasks ───────────────────────
    {
        id: 't4-1',
        text: 'Bootloader & HAL',
        type: 'task',
        parent: 't4',
        start: d(2026, 4, 13),
        end: d(2026, 4, 30),
        progress: 80,
        progressStatus: 'in-progress',
        assigned: 'D. Khan',
    },
    {
        id: 't4-1a',
        text: 'Hardware Init',
        type: 'task',
        parent: 't4-1',
        start: d(2026, 4, 13),
        end: d(2026, 4, 21),
        progress: 100,
        progressStatus: 'completed',
        assigned: 'D. Khan',
    },
    {
        id: 't4-1b',
        text: 'Memory Map & Linker',
        type: 'task',
        parent: 't4-1',
        start: d(2026, 4, 22),
        end: d(2026, 4, 30),
        progress: 60,
        progressStatus: 'in-progress',
        assigned: 'D. Khan',
    },
    {
        id: 't4-2',
        text: 'Sensor Drivers',
        type: 'task',
        parent: 't4',
        start: d(2026, 5, 1),
        end: d(2026, 5, 25),
        progress: 40,
        progressStatus: 'in-progress',
        assigned: 'D. Khan',
    },
    {
        id: 't4-2a',
        text: 'Accelerometer Driver',
        type: 'task',
        parent: 't4-2',
        start: d(2026, 5, 1),
        end: d(2026, 5, 12),
        progress: 70,
        progressStatus: 'in-progress',
        assigned: 'D. Khan',
    },
    {
        id: 't4-2b',
        text: 'Heart Rate Sensor Driver',
        type: 'task',
        parent: 't4-2',
        start: d(2026, 5, 13),
        end: d(2026, 5, 25),
        progress: 10,
        progressStatus: 'in-progress',
        assigned: 'D. Khan',
    },
    {
        id: 't4-3',
        text: 'Application Layer',
        type: 'task',
        parent: 't4',
        start: d(2026, 5, 26),
        end: d(2026, 6, 15),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'D. Khan',
    },
    {
        id: 't4b',
        text: 'Companion App (iOS/Android)',
        type: 'task',
        parent: 'p2',
        start: d(2026, 4, 20),
        end: d(2026, 6, 12),
        progress: 40,
        progressStatus: 'in-progress',
        assigned: 'J. Lopez',
    },
    {
        id: 't4c',
        text: 'Cloud Backend',
        type: 'task',
        parent: 'p2',
        start: d(2026, 5, 4),
        end: d(2026, 6, 15),
        progress: 30,
        progressStatus: 'in-progress',
        assigned: 'T. Nakamura',
    },
    {
        id: 'm1',
        text: 'Design Freeze',
        type: 'milestone',
        start: d(2026, 6, 15),
        end: d(2026, 6, 15),
        progress: 0,
        progressStatus: 'not-started',
    },

    // ─── PHASE 3: VERIFICATION & VALIDATION ────────────────────────────────
    {
        id: 'p3',
        text: 'Verification & Validation',
        type: 'category',
        start: d(2026, 6, 16),
        end: d(2026, 9, 25),
        progress: 10,
        progressStatus: 'in-progress',
    },
    {
        id: 't5',
        text: 'Verification Testing',
        type: 'task',
        parent: 'p3',
        start: d(2026, 6, 16),
        end: d(2026, 7, 31),
        progress: 25,
        progressStatus: 'in-progress',
        assigned: 'S. Mehta',
    },
    {
        id: 't5b',
        text: 'Software V&V (IEC 62304)',
        type: 'task',
        parent: 'p3',
        start: d(2026, 6, 22),
        end: d(2026, 8, 14),
        progress: 15,
        progressStatus: 'in-progress',
        assigned: 'S. Mehta',
    },
    {
        id: 't5c',
        text: 'Biocompatibility Tests (ISO 10993)',
        type: 'task',
        parent: 'p3',
        start: d(2026, 7, 1),
        end: d(2026, 8, 28),
        progress: 5,
        progressStatus: 'in-progress',
        assigned: 'External Lab',
    },
    {
        id: 't5d',
        text: 'EMC / Electrical Safety (IEC 60601)',
        type: 'task',
        parent: 'p3',
        start: d(2026, 7, 13),
        end: d(2026, 8, 21),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'External Lab',
    },
    {
        id: 't6',
        text: 'Clinical Validation',
        type: 'task',
        parent: 'p3',
        start: d(2026, 7, 20),
        end: d(2026, 9, 10),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Dr. Banerjee',
    },
    {
        id: 't6b',
        text: 'Usability Validation',
        type: 'task',
        parent: 'p3',
        start: d(2026, 8, 17),
        end: d(2026, 9, 25),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'N. Wong',
    },

    // ─── PHASE 4: REGULATORY ───────────────────────────────────────────────
    {
        id: 'p4',
        text: 'Regulatory Submission',
        type: 'category',
        start: d(2026, 9, 11),
        end: d(2026, 12, 5),
        progress: 0,
        progressStatus: 'not-started',
    },
    {
        id: 't7',
        text: 'Technical File Compilation',
        type: 'task',
        parent: 'p4',
        start: d(2026, 9, 11),
        end: d(2026, 10, 25),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'P. Joshi',
    },
    // ── Nested under t7: depth-2 + depth-3 sub-tasks ───────────────────────
    {
        id: 't7-1',
        text: 'Design History File',
        type: 'task',
        parent: 't7',
        start: d(2026, 9, 11),
        end: d(2026, 9, 30),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'P. Joshi',
    },
    {
        id: 't7-2',
        text: 'Risk Management File',
        type: 'task',
        parent: 't7',
        start: d(2026, 10, 1),
        end: d(2026, 10, 18),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'L. Becker',
    },
    {
        id: 't7-2a',
        text: 'Hazard Analysis Update',
        type: 'task',
        parent: 't7-2',
        start: d(2026, 10, 1),
        end: d(2026, 10, 10),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'L. Becker',
    },
    {
        id: 't7-2b',
        text: 'Risk Control Verification',
        type: 'task',
        parent: 't7-2',
        start: d(2026, 10, 11),
        end: d(2026, 10, 18),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'L. Becker',
    },
    {
        id: 't7-3',
        text: 'Clinical Evidence Summary',
        type: 'task',
        parent: 't7',
        start: d(2026, 10, 19),
        end: d(2026, 10, 25),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Dr. Banerjee',
    },
    {
        id: 't7b',
        text: 'Clinical Evaluation Report',
        type: 'task',
        parent: 'p4',
        start: d(2026, 9, 21),
        end: d(2026, 10, 30),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Dr. Banerjee',
    },
    {
        id: 't7c',
        text: 'Post-Market Surveillance Plan',
        type: 'task',
        parent: 'p4',
        start: d(2026, 10, 1),
        end: d(2026, 10, 25),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'P. Joshi',
    },
    {
        id: 't8',
        text: 'Notified Body Submission',
        type: 'task',
        parent: 'p4',
        start: d(2026, 10, 26),
        end: d(2026, 11, 30),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'P. Joshi',
    },
    {
        id: 't8b',
        text: 'NB Review & Q&A',
        type: 'task',
        parent: 'p4',
        start: d(2026, 11, 16),
        end: d(2026, 12, 5),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'P. Joshi',
    },
    {
        id: 'm2',
        text: 'CE Mark Approval',
        type: 'milestone',
        start: d(2026, 12, 8),
        end: d(2026, 12, 8),
        progress: 0,
        progressStatus: 'not-started',
    },

    // ─── PHASE 5: COMMERCIAL LAUNCH (2027) ─────────────────────────────────
    {
        id: 'p5',
        text: 'Commercial Launch',
        type: 'category',
        start: d(2026, 12, 9),
        end: d(2027, 3, 1),
        progress: 0,
        progressStatus: 'not-started',
    },
    {
        id: 't9',
        text: 'Production Ramp-up',
        type: 'task',
        parent: 'p5',
        start: d(2026, 12, 9),
        end: d(2027, 2, 15),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Operations',
    },
    {
        id: 't9b',
        text: 'Supplier Qualification',
        type: 'task',
        parent: 'p5',
        start: d(2026, 12, 9),
        end: d(2027, 1, 20),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Procurement',
    },
    {
        id: 't9c',
        text: 'Sales Training',
        type: 'task',
        parent: 'p5',
        start: d(2027, 1, 5),
        end: d(2027, 2, 5),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Commercial',
    },
    {
        id: 't9d',
        text: 'Marketing Launch Campaign',
        type: 'task',
        parent: 'p5',
        start: d(2027, 1, 26),
        end: d(2027, 2, 28),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Marketing',
    },
    {
        id: 'm3',
        text: 'Market Release',
        type: 'milestone',
        start: d(2027, 3, 1),
        end: d(2027, 3, 1),
        progress: 0,
        progressStatus: 'not-started',
    },

    // ─── PHASE 6: POST-MARKET (2027 → 2028) ────────────────────────────────
    {
        id: 'p6',
        text: 'Post-Market Surveillance',
        type: 'category',
        start: d(2027, 3, 2),
        end: d(2028, 3, 31),
        progress: 0,
        progressStatus: 'not-started',
    },
    {
        id: 't10a',
        text: 'Field Performance Monitoring',
        type: 'task',
        parent: 'p6',
        start: d(2027, 3, 2),
        end: d(2028, 3, 31),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'PMS Team',
    },
    {
        id: 't10b',
        text: 'Customer Feedback Collection',
        type: 'task',
        parent: 'p6',
        start: d(2027, 4, 1),
        end: d(2028, 3, 31),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Support',
    },
    {
        id: 't10c',
        text: 'PSUR Compilation',
        type: 'task',
        parent: 'p6',
        start: d(2027, 9, 1),
        end: d(2027, 12, 15),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'P. Joshi',
    },
    {
        id: 't10d',
        text: 'First Annual Review',
        type: 'task',
        parent: 'p6',
        start: d(2028, 1, 15),
        end: d(2028, 3, 15),
        progress: 0,
        progressStatus: 'not-started',
        assigned: 'Quality',
    },
    {
        id: 'm4',
        text: '1-Year On-Market Review',
        type: 'milestone',
        start: d(2028, 3, 31),
        end: d(2028, 3, 31),
        progress: 0,
        progressStatus: 'not-started',
    },
];

export const SAMPLE_LINKS: GanttLink[] = [
    // Discovery
    { id: 'l0a', source: 't0a', target: 't0b', type: 'e2s' },
    { id: 'l0b', source: 't0b', target: 't0c', type: 's2s' },
    // Discovery → Design
    { id: 'l0c', source: 't0c', target: 't1', type: 'e2s' },

    // Design
    { id: 'l1', source: 't1', target: 't2', type: 'e2s' },
    { id: 'l1b', source: 't1', target: 't1b', type: 's2s' },
    { id: 'l1c', source: 't2', target: 't2b', type: 's2s' },
    { id: 'l1d', source: 't2b', target: 't2c', type: 's2s' },

    // Design → Development
    { id: 'l2', source: 't2', target: 't3', type: 'e2s' },

    // Development
    { id: 'l3', source: 't3', target: 't3b', type: 's2s' },
    { id: 'l4', source: 't3', target: 't4', type: 'e2s' },
    { id: 'l4b', source: 't4', target: 't4b', type: 's2s' },
    { id: 'l4c', source: 't4b', target: 't4c', type: 's2s' },

    // Firmware sub-tasks (nested under t4)
    { id: 'l4-1', source: 't4-1', target: 't4-2', type: 'e2s' },
    { id: 'l4-2', source: 't4-2', target: 't4-3', type: 'e2s' },
    { id: 'l4-1ab', source: 't4-1a', target: 't4-1b', type: 'e2s' },
    { id: 'l4-2ab', source: 't4-2a', target: 't4-2b', type: 'e2s' },

    // Development → Design Freeze
    { id: 'l5', source: 't4', target: 'm1', type: 'e2s' },
    { id: 'l5b', source: 't4c', target: 'm1', type: 'e2s' },

    // V&V
    { id: 'l6', source: 'm1', target: 't5', type: 'e2s' },
    { id: 'l6b', source: 't5', target: 't5b', type: 's2s' },
    { id: 'l6c', source: 't5', target: 't5c', type: 's2s' },
    { id: 'l6d', source: 't5b', target: 't5d', type: 's2s' },
    { id: 'l7', source: 't5', target: 't6', type: 's2s' },
    { id: 'l7b', source: 't6', target: 't6b', type: 's2s' },

    // V&V → Regulatory
    { id: 'l8', source: 't6', target: 't7', type: 'e2s' },
    { id: 'l8b', source: 't7', target: 't7b', type: 's2s' },
    { id: 'l8c', source: 't7', target: 't7c', type: 's2s' },

    // Technical File Compilation sub-tasks (nested under t7)
    { id: 'l7-1', source: 't7-1', target: 't7-2', type: 'e2s' },
    { id: 'l7-2', source: 't7-2', target: 't7-3', type: 'e2s' },
    { id: 'l7-2ab', source: 't7-2a', target: 't7-2b', type: 'e2s' },

    // Regulatory
    { id: 'l9', source: 't7', target: 't8', type: 'e2s' },
    { id: 'l9b', source: 't8', target: 't8b', type: 'e2s' },
    { id: 'l10', source: 't8b', target: 'm2', type: 'e2s' },

    // Launch
    { id: 'l11', source: 'm2', target: 't9', type: 'e2s' },
    { id: 'l11b', source: 't9', target: 't9b', type: 's2s' },
    { id: 'l11c', source: 't9b', target: 't9c', type: 'e2s' },
    { id: 'l11d', source: 't9c', target: 't9d', type: 's2s' },
    { id: 'l12', source: 't9', target: 'm3', type: 'e2s' },

    // Post-Market
    { id: 'l13', source: 'm3', target: 't10a', type: 'e2s' },
    { id: 'l13b', source: 't10a', target: 't10b', type: 's2s' },
    { id: 'l13c', source: 't10b', target: 't10c', type: 's2s' },
    { id: 'l13d', source: 't10c', target: 't10d', type: 'e2s' },
    { id: 'l14', source: 't10d', target: 'm4', type: 'e2s' },
];

// Span ~3 years (mid-2025 → mid-2028) so multiple year labels appear in the
// header and the user can zoom out to see the full programme.
export const SAMPLE_DOMAIN: [Date, Date] = [d(2025, 6, 1), d(2028, 6, 30)];
