import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { currentContent, previousContent, versionName } = await req.json();
    
    if (!currentContent || !previousContent) {
      return new Response(
        JSON.stringify({ error: "Missing required content for comparison" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const systemPrompt = `You are an expert document analyst specializing in version control and change management for medical device documentation. Your task is to compare two versions of a document and provide a comprehensive analysis with highlighted changes.

IMPORTANT FORMATTING INSTRUCTIONS:
- Use special markers to highlight different types of changes:
  - Wrap ADDITIONS (new content) with: [ADD]content here[/ADD]
  - Wrap DELETIONS (removed content) with: [DEL]content here[/DEL]
  - Wrap MODIFICATIONS (changed content) with: [MOD]content here[/MOD]
- Use these markers inline within your analysis to highlight specific text changes
- Be specific about what was added, deleted, or modified

Instructions:
1. Analyze the differences between the current and previous versions
2. Identify additions, deletions, and modifications
3. Assess the impact and significance of changes
4. Provide actionable recommendations
5. Format your response in clear, structured markdown
6. Be specific and detailed in your analysis
7. Focus on regulatory compliance and quality management aspects
8. Use the special markers [ADD], [DEL], and [MOD] to highlight changes inline`;

    const userPrompt = `Please compare these two document versions and provide a detailed analysis with highlighted changes:

CURRENT VERSION:
${currentContent}

PREVIOUS VERSION (${versionName}):
${previousContent}

Please provide:
1. Executive Summary of Changes (highlight key changes using the markers)
2. Detailed Change Analysis:
   - Additions: List new content wrapped with [ADD]...[/ADD]
   - Deletions: List removed content wrapped with [DEL]...[/DEL]
   - Modifications: List changed content wrapped with [MOD]...[/MOD]
3. Impact Assessment (High/Medium/Low impact changes)
4. Risk Analysis
5. Compliance Implications
6. Recommendations for Review and Action
7. Next Steps

Format the response in clear markdown with proper headings and bullet points. Use the special markers to highlight specific changes inline.`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
        max_tokens: 2000,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limits exceeded. Please try again later." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "Payment required. Please add credits to your Lovable AI workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      return new Response(
        JSON.stringify({ error: "AI gateway error" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("No content generated by AI");
    }

    return new Response(
      JSON.stringify({ success: true, content }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error) {
    console.error("Error in document version comparison:", error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : "Unknown error occurred" 
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
