/**
 * AI Change Tracking Service
 * Tracks and highlights content that has been modified or generated by AI
 */

export interface ChangeTracker {
  originalContent: string;
  modifiedContent: string;
  changeType: 'ai-generated' | 'ai-modified' | 'company-data' | 'template-original';
  timestamp: Date;
  source?: string;
}

export class AIChangeTrackingService {
  private static changes: Map<string, ChangeTracker> = new Map();

  /**
   * Track a change made by AI or automated population
   */
  static trackChange(contentId: string, originalContent: string, newContent: string, changeType: ChangeTracker['changeType'], source?: string) {
    this.changes.set(contentId, {
      originalContent,
      modifiedContent: newContent,
      changeType,
      timestamp: new Date(),
      source
    });
  }

  /**
   * Apply yellow highlighting to AI-modified content
   */
  static highlightAIChanges(content: string, contentId: string): string {
    const change = this.changes.get(contentId);
    if (!change || change.changeType === 'template-original') {
      return content;
    }

    // Apply yellow highlighting for AI changes
    if (change.changeType === 'ai-generated' || change.changeType === 'ai-modified') {
      return `<span style="background-color: #fef08a; padding: 2px 4px; border-radius: 3px;" title="AI Generated/Modified Content">${content}</span>`;
    }

    // Apply light blue highlighting for company data auto-population
    if (change.changeType === 'company-data') {
      return `<span style="background-color: #dbeafe; padding: 2px 4px; border-radius: 3px;" title="Auto-populated from Company Data">${content}</span>`;
    }

    return content;
  }

  /**
   * Get all changes for reporting
   */
  static getAllChanges(): Map<string, ChangeTracker> {
    return this.changes;
  }

  /**
   * Clear all tracked changes
   */
  static clearChanges() {
    this.changes.clear();
  }

  /**
   * Mark content as AI-generated with enhanced yellow highlighting and inline display
   */
  static markAsAIGenerated(content: string): string {
    return `<span style="background-color: #fef08a; padding: 2px 4px; border-radius: 3px; font-weight: 500; border-left: 3px solid #f59e0b;" title="AI Generated Content">⚡ ${content}</span>`;
  }

  /**
   * Mark content as auto-populated from company data
   */
  static markAsCompanyData(content: string): string {
    return `<span style="background-color: #dbeafe; padding: 2px 4px; border-radius: 3px; font-weight: 500;" title="Auto-populated from Company Settings">📊 ${content}</span>`;
  }

  /**
   * Check if content has been modified by AI
   */
  static isAIModified(contentId: string): boolean {
    const change = this.changes.get(contentId);
    return change && (change.changeType === 'ai-generated' || change.changeType === 'ai-modified') || false;
  }
}