import { supabase } from '@/integrations/supabase/client';
import { CAPARecord, CAPAAction, CAPAEvidence, CAPAStateTransition, CAPAStatus, CAPA_STATE_GATES } from '@/types/capa';
import { HELIX_NODE_CONFIGS } from '@/config/helixNodeConfig';

// Type for database insert/update operations
type CAPARecordInsert = {
  company_id: string;
  product_id?: string | null;
  source_type: string;
  source_id?: string | null;
  source_device_id?: string | null; // For device escalation
  source_node_id?: string | null; // For device escalation
  capa_type: string;
  problem_description: string;
  immediate_correction?: string | null;
  severity?: number | null;
  probability?: number | null;
  status?: string;
  owner_id?: string | null;
  quality_lead_id?: string | null;
  technical_lead_id?: string | null;
  investigation_team?: any;
  rca_methodology?: string | null;
  root_cause_summary?: string | null;
  root_cause_category?: string | null;
  requires_regulatory_update?: boolean;
  regulatory_impact_description?: string | null;
  affected_documents?: any;
  affected_requirements?: any;
  voe_plan?: string | null;
  voe_success_criteria?: string | null;
  voe_result?: string | null;
  target_investigation_date?: string | null;
  target_implementation_date?: string | null;
  target_verification_date?: string | null;
  target_closure_date?: string | null;
  created_by: string;
};

// Internal type with capa_id for database operations
type CAPARecordInsertWithId = CAPARecordInsert & { capa_id: string };

type CAPARecordUpdate = Partial<Omit<CAPARecordInsert, 'company_id' | 'created_by'>>;

export const capaService = {
  // ============================================
  // CAPA RECORDS
  // ============================================
  
  async getCAPAsByCompany(companyId: string): Promise<CAPARecord[]> {
    const { data, error } = await supabase
      .from('capa_records')
      .select('*')
      .eq('company_id', companyId)
      .order('created_at', { ascending: false });
    
    if (error) throw error;
    return (data || []) as unknown as CAPARecord[];
  },

  async getCAPAsByProduct(productId: string): Promise<CAPARecord[]> {
    const { data, error } = await supabase
      .from('capa_records')
      .select('*')
      .eq('product_id', productId)
      .order('created_at', { ascending: false });
    
    if (error) throw error;
    return (data || []) as unknown as CAPARecord[];
  },

  async getCAPAById(capaId: string): Promise<CAPARecord | null> {
    const { data, error } = await supabase
      .from('capa_records')
      .select('*')
      .eq('id', capaId)
      .maybeSingle();
    
    if (error) throw error;
    return data as unknown as CAPARecord | null;
  },

  async createCAPA(record: CAPARecordInsert): Promise<CAPARecord> {
    // capa_id is auto-generated by database trigger, so we pass an empty string
    // which the trigger will replace with the generated ID
    const insertData = {
      ...record,
      capa_id: '' // Trigger will auto-generate this
    };
    
    const { data, error } = await supabase
      .from('capa_records')
      .insert([insertData])
      .select()
      .single();
    
    if (error) throw error;
    return data as unknown as CAPARecord;
  },

  async updateCAPA(id: string, updates: CAPARecordUpdate): Promise<CAPARecord> {
    const { data, error } = await supabase
      .from('capa_records')
      .update(updates)
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return data as unknown as CAPARecord;
  },

  async deleteCAPA(id: string): Promise<void> {
    const { error } = await supabase
      .from('capa_records')
      .delete()
      .eq('id', id);
    
    if (error) throw error;
  },

  // ============================================
  // STATE TRANSITIONS
  // ============================================

  async transitionCAPAState(
    capaId: string,
    fromStatus: CAPAStatus | null,
    toStatus: CAPAStatus,
    userId: string,
    reason?: string
  ): Promise<void> {
    // Validate transition is allowed
    const allowedTransitions = CAPA_STATE_GATES[fromStatus || 'draft'];
    if (!allowedTransitions?.includes(toStatus)) {
      throw new Error(`Invalid state transition from ${fromStatus} to ${toStatus}`);
    }

    // Start transaction-like operations
    const { error: transitionError } = await supabase
      .from('capa_state_transitions')
      .insert({
        capa_id: capaId,
        from_status: fromStatus,
        to_status: toStatus,
        transitioned_by: userId,
        transition_reason: reason
      });

    if (transitionError) throw transitionError;

    // Update CAPA status
    const updateData: any = { status: toStatus };
    
    // Handle closure
    if (toStatus === 'closed') {
      updateData.closure_date = new Date().toISOString();
      updateData.closed_by = userId;
    }

    const { error: updateError } = await supabase
      .from('capa_records')
      .update(updateData)
      .eq('id', capaId);

    if (updateError) throw updateError;
  },

  async getCAPATransitions(capaId: string): Promise<CAPAStateTransition[]> {
    const { data, error } = await supabase
      .from('capa_state_transitions')
      .select('*')
      .eq('capa_id', capaId)
      .order('created_at', { ascending: true });
    
    if (error) throw error;
    return (data || []) as unknown as CAPAStateTransition[];
  },

  // ============================================
  // CAPA ACTIONS
  // ============================================

  async getCAPAActions(capaId: string): Promise<CAPAAction[]> {
    const { data, error } = await supabase
      .from('capa_actions')
      .select('*')
      .eq('capa_id', capaId)
      .order('created_at', { ascending: true });
    
    if (error) throw error;
    return (data || []) as unknown as CAPAAction[];
  },

  async createCAPAAction(action: Omit<CAPAAction, 'id' | 'created_at' | 'updated_at'>): Promise<CAPAAction> {
    const { data, error } = await supabase
      .from('capa_actions')
      .insert(action)
      .select()
      .single();
    
    if (error) throw error;
    return data as unknown as CAPAAction;
  },

  async updateCAPAAction(id: string, updates: Partial<CAPAAction>): Promise<CAPAAction> {
    const { data, error } = await supabase
      .from('capa_actions')
      .update(updates)
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return data as unknown as CAPAAction;
  },

  async deleteCAPAAction(id: string): Promise<void> {
    const { error } = await supabase
      .from('capa_actions')
      .delete()
      .eq('id', id);
    
    if (error) throw error;
  },

  // ============================================
  // CAPA EVIDENCE
  // ============================================

  async getCAPAEvidence(capaId: string): Promise<CAPAEvidence[]> {
    const { data, error } = await supabase
      .from('capa_evidence')
      .select('*')
      .eq('capa_id', capaId)
      .order('created_at', { ascending: false });
    
    if (error) throw error;
    return (data || []) as unknown as CAPAEvidence[];
  },

  async uploadCAPAEvidence(
    capaId: string,
    file: File,
    evidenceType: CAPAEvidence['evidence_type'],
    description: string | undefined,
    userId: string
  ): Promise<CAPAEvidence> {
    // Upload file to storage
    const filePath = `capa/${capaId}/${Date.now()}_${file.name}`;
    const { error: uploadError } = await supabase.storage
      .from('capa-evidence')
      .upload(filePath, file);

    if (uploadError) throw uploadError;

    // Create evidence record
    const { data, error } = await supabase
      .from('capa_evidence')
      .insert({
        capa_id: capaId,
        evidence_type: evidenceType,
        file_name: file.name,
        storage_path: filePath,
        description,
        uploaded_by: userId
      })
      .select()
      .single();

    if (error) throw error;
    return data as unknown as CAPAEvidence;
  },

  async deleteCAPAEvidence(id: string, storagePath: string): Promise<void> {
    // Delete from storage
    await supabase.storage
      .from('capa-evidence')
      .remove([storagePath]);

    // Delete record
    const { error } = await supabase
      .from('capa_evidence')
      .delete()
      .eq('id', id);

    if (error) throw error;
  },

  // ============================================
  // ANALYTICS
  // ============================================

  async getCAPAAnalytics(companyId: string): Promise<{
    total: number;
    open: number;
    overdue: number;
    closedThisMonth: number;
    byStatus: Record<CAPAStatus, number>;
    bySourceType: Record<string, number>;
  }> {
    const { data, error } = await supabase
      .from('capa_records')
      .select('*')
      .eq('company_id', companyId);

    if (error) throw error;

    const records = (data || []) as unknown as CAPARecord[];
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);

    const openStatuses: CAPAStatus[] = ['draft', 'triage', 'investigation', 'planning', 'implementation', 'verification'];
    
    const byStatus = records.reduce((acc, r) => {
      acc[r.status] = (acc[r.status] || 0) + 1;
      return acc;
    }, {} as Record<CAPAStatus, number>);

    const bySourceType = records.reduce((acc, r) => {
      acc[r.source_type] = (acc[r.source_type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return {
      total: records.length,
      open: records.filter(r => openStatuses.includes(r.status)).length,
      overdue: records.filter(r => {
        if (!openStatuses.includes(r.status)) return false;
        const targetDate = r.target_closure_date;
        return targetDate && new Date(targetDate) < now;
      }).length,
      closedThisMonth: records.filter(r => {
        if (r.status !== 'closed' || !r.closure_date) return false;
        return new Date(r.closure_date) >= startOfMonth;
      }).length,
      byStatus,
      bySourceType
    };
  },

  async getCAPAAnalyticsByProduct(productId: string): Promise<{
    total: number;
    open: number;
    overdue: number;
    closedThisMonth: number;
    byStatus: Record<CAPAStatus, number>;
    bySourceType: Record<string, number>;
  }> {
    const { data, error } = await supabase
      .from('capa_records')
      .select('*')
      .eq('product_id', productId);

    if (error) throw error;

    const records = (data || []) as unknown as CAPARecord[];
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);

    const openStatuses: CAPAStatus[] = ['draft', 'triage', 'investigation', 'planning', 'implementation', 'verification'];
    
    const byStatus = records.reduce((acc, r) => {
      acc[r.status] = (acc[r.status] || 0) + 1;
      return acc;
    }, {} as Record<CAPAStatus, number>);

    const bySourceType = records.reduce((acc, r) => {
      acc[r.source_type] = (acc[r.source_type] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return {
      total: records.length,
      open: records.filter(r => openStatuses.includes(r.status)).length,
      overdue: records.filter(r => {
        if (!openStatuses.includes(r.status)) return false;
        const targetDate = r.target_closure_date;
        return targetDate && new Date(targetDate) < now;
      }).length,
      closedThisMonth: records.filter(r => {
        if (r.status !== 'closed' || !r.closure_date) return false;
        return new Date(r.closure_date) >= startOfMonth;
      }).length,
      byStatus,
      bySourceType
    };
  },

  // ============================================
  // EVIDENCE ESCALATION
  // ============================================

  /**
   * Create an escalated CAPA from a device-level node failure
   * This demonstrates "Loop Closure" by connecting device failures to company-wide CAPA
   */
  async createEscalatedCAPA(
    companyId: string,
    sourceDeviceId: string,
    sourceNodeId: string,
    problemDescription: string,
    userId: string
  ): Promise<CAPARecord> {
    // Get the node config for better labeling
    const nodeConfig = HELIX_NODE_CONFIGS.find(n => n.id === sourceNodeId);
    const nodeLabel = nodeConfig?.label || sourceNodeId;
    
    // Build insert data with capa_id (trigger will auto-generate)
    const insertData = {
      company_id: companyId,
      product_id: sourceDeviceId,
      source_type: 'internal',
      source_device_id: sourceDeviceId,
      source_node_id: sourceNodeId,
      capa_type: 'corrective',
      problem_description: `[Escalated from Device Node: ${nodeLabel}]\n\n${problemDescription}`,
      status: 'draft',
      severity: 3, // Default to moderate severity for escalated items
      probability: 3,
      created_by: userId,
      capa_id: '' // Trigger will auto-generate this
    };

    const { data, error } = await supabase
      .from('capa_records')
      .insert([insertData])
      .select()
      .single();

    if (error) throw error;
    return data as unknown as CAPARecord;
  },

  /**
   * Get count of CAPAs escalated from devices (for company CAPA node display)
   */
  async getEscalatedCAPACount(companyId: string): Promise<number> {
    const { count, error } = await supabase
      .from('capa_records')
      .select('*', { count: 'exact', head: true })
      .eq('company_id', companyId)
      .not('source_device_id', 'is', null)
      .in('status', ['draft', 'triage', 'investigation', 'planning', 'implementation', 'verification']);

    if (error) throw error;
    return count || 0;
  },

  /**
   * Get CAPAs escalated from a specific device
   */
  async getEscalatedCAPAsByDevice(deviceId: string): Promise<CAPARecord[]> {
    const { data, error } = await supabase
      .from('capa_records')
      .select('*')
      .eq('source_device_id', deviceId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return (data || []) as unknown as CAPARecord[];
  }
};
