import { supabase } from '@/integrations/supabase/client';
import { capaService } from '@/services/capaService';

export type EscalationTier = 'hard' | 'soft' | 'none';

export interface EscalationResult {
  tier: EscalationTier;
  capaId?: string;
  capaDisplayId?: string;
  ccrId?: string;
  ccrDisplayId?: string;
  message: string;
}

interface PMSEventInput {
  id: string;
  company_id: string;
  product_id: string;
  event_type: string;
  severity?: string;
  description: string;
}

// Map PMS severity to CAPA severity (1-5 scale)
function mapPMSSeverityToCAPA(severity?: string): number {
  switch (severity) {
    case 'critical': return 5;
    case 'serious': return 4;
    case 'moderate': return 2;
    case 'minor': return 1;
    default: return 2;
  }
}

function determineTier(event: PMSEventInput): EscalationTier {
  if (event.severity === 'critical' || event.event_type === 'adverse_event') {
    return 'hard';
  }
  if (event.severity === 'serious' || event.event_type === 'device_malfunction') {
    return 'soft';
  }
  return 'none';
}

export const pmsEscalationService = {
  async evaluateEscalation(event: PMSEventInput): Promise<EscalationResult> {
    const tier = determineTier(event);

    if (tier === 'none') {
      return { tier, message: 'Event logged. No immediate escalation required.' };
    }

    const { data: { user } } = await supabase.auth.getUser();
    const userId = user?.id || '';

    // Create CAPA for both hard and soft triggers
    const capa = await capaService.createCAPA({
      company_id: event.company_id,
      product_id: event.product_id,
      source_type: 'pms_event',
      source_id: event.id,
      capa_type: 'corrective',
      problem_description: `[PMS Event] ${event.description}`,
      severity: mapPMSSeverityToCAPA(event.severity),
      created_by: userId,
    });

    const result: EscalationResult = {
      tier,
      capaId: capa.id,
      capaDisplayId: capa.capa_id,
      message: '',
    };

    // Hard trigger: also create CCR
    if (tier === 'hard') {
      const { data: ccr, error: ccrError } = await supabase
        .from('change_control_requests')
        .insert({
          company_id: event.company_id,
          product_id: event.product_id,
          source_type: 'capa',
          source_capa_id: capa.id,
          change_type: 'design',
          title: `Field Safety: ${event.description.substring(0, 80)}`,
          description: `Auto-created from PMS event escalation. Original event: ${event.description}`,
          risk_impact: 'high',
          regulatory_impact: true,
          created_by: userId,
          ccr_id: '', // auto-generated by trigger
        } as any)
        .select()
        .single();

      if (!ccrError && ccr) {
        result.ccrId = ccr.id;
        result.ccrDisplayId = ccr.ccr_id;

        // Update pms_event with both escalated IDs
        await supabase
          .from('pms_events')
          .update({
            escalated_capa_id: capa.id,
            escalated_ccr_id: ccr.id,
          } as any)
          .eq('id', event.id);

        result.message = `A CAPA (${capa.capa_id}) and CCR (${ccr.ccr_id}) have been automatically initiated due to event severity.`;
      }
    } else {
      // Soft trigger: CAPA only
      await supabase
        .from('pms_events')
        .update({ escalated_capa_id: capa.id } as any)
        .eq('id', event.id);

      result.message = `A CAPA (${capa.capa_id}) has been initiated. You may optionally create a CCR.`;
    }

    return result;
  },

  async linkEventToDesignObjects(
    eventId: string,
    requirementIds: string[],
    hazardIds: string[]
  ): Promise<void> {
    await supabase
      .from('pms_events')
      .update({
        linked_requirement_ids: requirementIds,
        linked_hazard_ids: hazardIds,
      } as any)
      .eq('id', eventId);
  },
};
