import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { trackTokenUsage, extractLovableAIUsage } from "../_shared/token-tracking.ts";

declare const EdgeRuntime: { waitUntil(promise: Promise<unknown>): void };

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { prompt, sectionTitle, currentContent, companyId, referenceContext, outputLanguage } = await req.json();
    console.log('[ai-content-generator] Request received:', { sectionTitle, hasPrompt: !!prompt, companyId, hasReferenceContext: !!referenceContext, outputLanguage });

    if (!prompt) {
      throw new Error('Prompt is required');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    // Build the AI prompt with context
    const systemPrompt = `You are an expert technical writer specializing in medical device documentation and quality management systems.

Guidelines:
- Use professional medical device industry language
- Follow ISO 13485 and FDA 21 CFR Part 820 standards
- Be specific and actionable
- Include relevant compliance references when appropriate
- Structure content logically with clear sections
- Ensure content is comprehensive yet concise
- CRITICAL: Return ONLY raw HTML content - NO markdown, NO code blocks, NO \`\`\`html tags
- Start your response directly with HTML tags like <p>, <ul>, <h3>, etc.
- Do NOT wrap your response in markdown code fences (\`\`\`html or \`\`\`)
- Do NOT include any preamble, explanations, or introductory text
- Use well-formatted HTML with semantic tags: <p>, <ul>, <ol>, <li>, <h3>, <h4>, <strong>, <em>, <a>
- Use proper HTML structure for lists, paragraphs, and headings
- Make links clickable using <a href="..."> tags where relevant

${referenceContext ? `IMPORTANT: The following reference documents have been provided as context. Use them as the PRIMARY source of truth for generating content. Adapt terminology, structure, and details from these documents.

--- REFERENCE DOCUMENTS ---
${referenceContext}
--- END REFERENCE DOCUMENTS ---` : ''}

${outputLanguage && outputLanguage !== 'en' ? `CRITICAL LANGUAGE INSTRUCTION: Generate ALL output text in ${
  outputLanguage === 'de' ? 'German (Deutsch)' :
  outputLanguage === 'fr' ? 'French (Français)' :
  outputLanguage === 'fi' ? 'Finnish (Suomi)' :
  'English'
}. Every heading, paragraph, list item, and label must be in this language. Do NOT mix languages.` : ''}`;

    const userPrompt = prompt;

    console.log('[ai-content-generator] Calling Lovable AI...');

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.7,
        max_tokens: 2000,
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('[ai-content-generator] AI API error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        throw new Error('Rate limit exceeded. Please try again in a moment.');
      }
      if (aiResponse.status === 402) {
        throw new Error('AI credits exhausted. Please add credits to continue.');
      }
      
      throw new Error(`AI API error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    console.log('[ai-content-generator] AI response received');

    const generatedContent = aiData.choices?.[0]?.message?.content;
    
    if (!generatedContent) {
      throw new Error('No content generated by AI');
    }

    // Track token usage in background if company_id provided
    if (companyId) {
      const usage = extractLovableAIUsage(aiData);
      if (usage) {
        EdgeRuntime.waitUntil(
          trackTokenUsage(companyId, 'gemini', usage)
        );
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true,
        content: generatedContent
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    console.error('[ai-content-generator] Error:', error);
    return new Response(
      JSON.stringify({ 
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred'
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
