import React from 'react';
import { Badge } from '@/components/ui/badge';
import { 
  Database, ArrowRightLeft, Users, Shield, FileCheck, 
  Calendar, AlertCircle, Lightbulb, CheckCircle2, Clock,
  Globe, FileText, Lock, Eye, Gauge, BookOpen, Scale
} from 'lucide-react';

// ─── Reusable Atoms ───

const HelpSection: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="space-y-2">
    <h4 className="font-semibold text-sm flex items-center gap-2">{title}</h4>
    {children}
  </div>
);

const TipCard: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="p-3 bg-primary/5 border border-primary/20 rounded-lg flex gap-2">
    <Lightbulb className="h-4 w-4 text-primary flex-shrink-0 mt-0.5" />
    <p className="text-xs text-muted-foreground">{children}</p>
  </div>
);

const WarningCard: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="p-3 bg-destructive/10 border border-destructive/30 rounded-lg flex gap-2">
    <AlertCircle className="h-4 w-4 text-destructive flex-shrink-0 mt-0.5" />
    <p className="text-xs text-muted-foreground">{children}</p>
  </div>
);

const InfoCard: React.FC<{ title: string; description: string }> = ({ title, description }) => (
  <div className="p-3 bg-muted/50 rounded-lg border">
    <h5 className="font-medium text-sm mb-1">{title}</h5>
    <p className="text-xs text-muted-foreground">{description}</p>
  </div>
);

const TimelineBadge: React.FC<{ date: string; status: 'active' | 'upcoming' | 'future' }> = ({ date, status }) => {
  const colors = {
    active: 'bg-green-100 text-green-800 border-green-300 dark:bg-green-900/30 dark:text-green-300 dark:border-green-700',
    upcoming: 'bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-700',
    future: 'bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-700',
  };
  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-medium border ${colors[status]}`}>
      <Clock className="h-3 w-3" />
      {date}
    </span>
  );
};

const ArticleBadge: React.FC<{ article: string }> = ({ article }) => (
  <Badge variant="outline" className="text-[10px] border-primary/30 text-primary gap-1">
    <Scale className="h-3 w-3" />
    {article}
  </Badge>
);

const StepList: React.FC<{ steps: string[] }> = ({ steps }) => (
  <ol className="space-y-2 text-sm text-muted-foreground">
    {steps.map((step, idx) => (
      <li key={idx} className="flex gap-2">
        <span className="flex-shrink-0 w-5 h-5 rounded-full bg-primary/10 text-primary text-xs flex items-center justify-center font-medium">
          {idx + 1}
        </span>
        <span>{step}</span>
      </li>
    ))}
  </ol>
);

const TimelineCallout: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="p-3 bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800 rounded-lg">
    <div className="flex items-center gap-2 mb-1">
      <Calendar className="h-4 w-4 text-blue-600 dark:text-blue-400" />
      <h5 className="font-semibold text-sm text-blue-800 dark:text-blue-300">{title}</h5>
    </div>
    <div className="text-xs text-blue-700 dark:text-blue-400">{children}</div>
  </div>
);

// ─── Main EHDS Overview Help ───

export const EHDSDataVaultHelp: React.FC = () => (
  <div className="space-y-6">
    <div className="flex flex-wrap gap-2 mb-3">
      <ArticleBadge article="EU Reg. 2025/327" />
      <TimelineBadge date="In Force: Mar 2025" status="active" />
      <TimelineBadge date="Primary Use: 2027" status="upcoming" />
      <TimelineBadge date="Secondary Use: 2029" status="future" />
    </div>

    <p className="text-sm text-muted-foreground">
      The <strong>European Health Data Space (EHDS)</strong> is EU Regulation 2025/327, adopted in March 2025. 
      It is the first cross-border framework that governs how health data — including data generated by medical 
      devices — is shared, accessed, and reused across the EU. If your device collects, processes, or stores 
      health data, <strong>you are a "Data Holder"</strong> under the EHDS.
    </p>

    <WarningCard>
      This is not optional. Unlike GDPR (which many medtech companies already comply with), the EHDS adds 
      <strong> new obligations specific to health data interoperability and sharing</strong>. Non-compliance 
      can block market access in the EU.
    </WarningCard>

    <HelpSection title="Why Does This Matter for Device Manufacturers?">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>The EHDS creates two categories of obligations:</p>
        <InfoCard 
          title="Primary Use (Chapter III)" 
          description="Your device's health data must be interoperable with the European Electronic Health Record Exchange Format (EEHRxF). Patients and healthcare providers must be able to access and transfer data across borders using standardized formats like HL7 FHIR." 
        />
        <InfoCard 
          title="Secondary Use (Chapter IV)" 
          description="Researchers, health authorities, and regulators can request access to your device's anonymized or pseudonymized data for public health research, clinical studies, or pharmacovigilance — through official Health Data Access Bodies (HDABs)." 
        />
      </div>
    </HelpSection>

    <HelpSection title="The 5 Modules in This Vault">
      <div className="space-y-2">
        <div className="p-3 bg-muted/50 rounded-lg border flex items-start gap-3">
          <Database className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <h5 className="font-medium text-sm">1. Dataset Library</h5>
            <p className="text-xs text-muted-foreground">Catalog every health dataset your devices generate. Map metadata to HealthDCAT-AP (the EU standard for dataset descriptions).</p>
          </div>
        </div>
        <div className="p-3 bg-muted/50 rounded-lg border flex items-start gap-3">
          <ArrowRightLeft className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <h5 className="font-medium text-sm">2. Translation Layer</h5>
            <p className="text-xs text-muted-foreground">Map your internal data fields to the EEHRxF standard (FHIR-based). This is how your data becomes "interoperable."</p>
          </div>
        </div>
        <div className="p-3 bg-muted/50 rounded-lg border flex items-start gap-3">
          <Users className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <h5 className="font-medium text-sm">3. Secondary Use</h5>
            <p className="text-xs text-muted-foreground">Manage incoming data access requests from Health Data Access Bodies (HDABs). Track permits, review trade secret protections.</p>
          </div>
        </div>
        <div className="p-3 bg-muted/50 rounded-lg border flex items-start gap-3">
          <Shield className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <h5 className="font-medium text-sm">4. Anonymization Lab</h5>
            <p className="text-xs text-muted-foreground">Define which PII fields to strip before releasing data. Calculate a Privacy Score. Choose between anonymization and pseudonymization.</p>
          </div>
        </div>
        <div className="p-3 bg-muted/50 rounded-lg border flex items-start gap-3">
          <FileCheck className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <h5 className="font-medium text-sm">5. Self-Declaration</h5>
            <p className="text-xs text-muted-foreground">Complete the Annex II checklist and generate your EHDS Declaration of Conformity — similar to what you do for CE marking, but for data compliance.</p>
          </div>
        </div>
      </div>
    </HelpSection>

    <HelpSection title="EHDS Timeline">
      <div className="space-y-2 text-sm text-muted-foreground">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="h-4 w-4 text-green-500" />
          <span><strong>March 2025:</strong> Regulation entered into force</span>
        </div>
        <div className="flex items-center gap-2">
          <Clock className="h-4 w-4 text-amber-500" />
          <span><strong>March 2027:</strong> EEHRxF mandatory for EHR systems (primary use)</span>
        </div>
        <div className="flex items-center gap-2">
          <Clock className="h-4 w-4 text-blue-500" />
          <span><strong>March 2029:</strong> Secondary use framework fully operational; dataset descriptions required</span>
        </div>
        <div className="flex items-center gap-2">
          <Clock className="h-4 w-4 text-blue-500" />
          <span><strong>2029–2031:</strong> Phased enforcement per member state; HDABs operational</span>
        </div>
      </div>
    </HelpSection>

    <HelpSection title="Compliance Mirror Philosophy">
      <p className="text-sm text-muted-foreground">
        This module does <strong>not</strong> touch your production data or patient records. It operates as a 
        <strong> "Compliance Mirror"</strong> — you describe your data here (metadata), map its structure, 
        and manage governance workflows. Think of it as your EHDS compliance evidence file, not a data warehouse.
      </p>
    </HelpSection>

    <TipCard>
      Start with the Dataset Library. Cataloging what health data your devices generate is the foundation 
      for everything else — translation, anonymization, and self-declaration all reference your dataset catalog.
    </TipCard>
  </div>
);

// ─── Tab 1: Dataset Library ───

export const EHDSDatasetsHelp: React.FC = () => (
  <div className="space-y-6">
    <div className="flex flex-wrap gap-2 mb-3">
      <ArticleBadge article="Art. 33 & Art. 55" />
      <TimelineBadge date="Required by: Mar 2029" status="future" />
    </div>

    <p className="text-sm text-muted-foreground">
      The Dataset Library is where you <strong>catalog every health dataset</strong> that your medical devices 
      generate, collect, or process. Under the EHDS, every Data Holder must maintain a machine-readable 
      description of their datasets using the <strong>HealthDCAT-AP</strong> metadata standard.
    </p>

    <TimelineCallout title="When Does This Apply?">
      <p>Dataset descriptions must be available by <strong>March 2029</strong> when the secondary use framework 
      becomes operational. However, you should start cataloging now — retroactively documenting datasets is 
      significantly harder and auditors will look for evidence of proactive compliance.</p>
    </TimelineCallout>

    <HelpSection title="What Is HealthDCAT-AP?">
      <p className="text-sm text-muted-foreground">
        HealthDCAT-AP (Health Data Catalogue Application Profile) is an EU-standard metadata format based on 
        DCAT-AP, adapted for health data. It describes <em>what</em> data you have, <em>how</em> it was collected, 
        <em>who</em> can access it, and <em>what format</em> it's in — without revealing the actual data.
      </p>
      <div className="space-y-2 mt-2">
        <InfoCard title="Think of it like a library card" description="HealthDCAT-AP is the 'card catalog' for your data. It tells regulators and researchers what datasets exist, their scope, quality, and access conditions — so they can request access without seeing the data first." />
      </div>
    </HelpSection>

    <HelpSection title="What Should You Catalog?">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>Any health-related data your device generates or processes:</p>
        <p>• <strong>Patient measurement data</strong> — vitals, readings, diagnostic outputs</p>
        <p>• <strong>Treatment records</strong> — therapy sessions, dosing data, device usage logs</p>
        <p>• <strong>Adverse event data</strong> — incident reports, complaint data with clinical context</p>
        <p>• <strong>Clinical investigation data</strong> — trial data, observational study outputs</p>
        <p>• <strong>Post-market surveillance data</strong> — PMCF results, PMS reports with patient data</p>
        <p>• <strong>Real-world evidence (RWE)</strong> — anonymized usage patterns, outcomes data</p>
      </div>
    </HelpSection>

    <HelpSection title="How to Catalog a Dataset">
      <StepList steps={[
        'Click "Add Dataset" and give it a clear, descriptive name (e.g., "Actiweight Patient Weight Measurements").',
        'Select the data categories — what types of health data does this dataset contain?',
        'Describe the collection method — how is the data gathered? (device sensor, manual entry, API, etc.)',
        'Specify the data format — FHIR, CSV, HL7v2, proprietary JSON, DICOM, etc.',
        'Estimate the volume — how many records? How often is new data added?',
        'Review the auto-generated HealthDCAT-AP metadata — Xyreg maps your inputs to the standard fields.',
        'Set the status to "Published" when the description is complete and accurate.',
        'Use "Export HealthDCAT-AP" to generate the machine-readable JSON for regulatory submissions.',
      ]} />
    </HelpSection>

    <HelpSection title="Accuracy Checks">
      <p className="text-sm text-muted-foreground">
        Article 55 requires Data Holders to ensure dataset descriptions remain <strong>accurate and up-to-date</strong>. 
        Xyreg tracks this with an accuracy check reminder. When a dataset's accuracy check is overdue, you'll see 
        an amber indicator. Review your dataset descriptions at least annually, or whenever the device software 
        changes the data it collects.
      </p>
    </HelpSection>

    <HelpSection title="Auditor Expectations">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>• <strong>Completeness:</strong> Every health dataset must have a catalog entry. Missing datasets = non-compliance.</p>
        <p>• <strong>Currency:</strong> Descriptions must match the current device version. Stale metadata is a common finding.</p>
        <p>• <strong>Machine-readability:</strong> The HealthDCAT-AP export should be valid JSON conforming to the EU schema.</p>
        <p>• <strong>Traceability:</strong> Each dataset should link to the product that generates it (if applicable).</p>
      </div>
    </HelpSection>

    <WarningCard>
      Do not confuse "datasets" with "documents." A dataset is raw health data (patient measurements, clinical 
      outcomes). A document is a regulatory artifact (a report, a form). The EHDS governs datasets, not documents.
    </WarningCard>

    <TipCard>
      For a small company like Actiweight with a single device, you likely have 2-4 datasets (e.g., patient 
      measurements, usage logs, adverse events). Start small — you can always add more later.
    </TipCard>
  </div>
);

// ─── Tab 2: Translation Layer ───

export const EHDSTranslationHelp: React.FC = () => (
  <div className="space-y-6">
    <div className="flex flex-wrap gap-2 mb-3">
      <ArticleBadge article="Art. 6, Art. 14" />
      <ArticleBadge article="EEHRxF / HL7 FHIR" />
      <TimelineBadge date="EHR Systems: Mar 2027" status="upcoming" />
      <TimelineBadge date="Device Data: Mar 2029" status="future" />
    </div>

    <p className="text-sm text-muted-foreground">
      The Translation Layer helps you <strong>map your internal data fields</strong> to the European Electronic 
      Health Record Exchange Format (EEHRxF). This is the core of EHDS interoperability — it ensures that 
      data from your device can be understood by any healthcare system in the EU, regardless of the country 
      or vendor.
    </p>

    <TimelineCallout title="When Does This Apply?">
      <p>EEHRxF is mandatory for <strong>EHR systems by March 2027</strong>. For medical device manufacturers, 
      the practical deadline is <strong>March 2029</strong> when secondary use obligations begin. However, 
      hospitals and health systems will start requiring FHIR-compatible data exports from devices much sooner. 
      <strong>Prepare now to stay competitive.</strong></p>
    </TimelineCallout>

    <HelpSection title="What Is EEHRxF?">
      <p className="text-sm text-muted-foreground">
        The European Electronic Health Record Exchange Format (EEHRxF) is the EU's standardized data format 
        for health records. It is built on <strong>HL7 FHIR R4</strong> (Fast Healthcare Interoperability 
        Resources) — the global standard for health data exchange.
      </p>
      <InfoCard 
        title="In Plain Language" 
        description="If your device stores 'patient_weight_kg' internally, EEHRxF says it should be mapped to a FHIR Observation resource with LOINC code 29463-7. The Translation Layer helps you create these mappings without writing code." 
      />
    </HelpSection>

    <HelpSection title="How Field Mapping Works">
      <StepList steps={[
        'Select a dataset from your Dataset Library.',
        'Xyreg lists all internal field names from your dataset description.',
        'For each field, select the corresponding EEHRxF standard field from the dropdown.',
        'Specify the FHIR Resource Type (e.g., Observation, Patient, Device, Procedure).',
        'Add the FHIR field path (e.g., "Observation.valueQuantity.value").',
        'Add transformation notes if the mapping requires conversion (e.g., "lbs → kg").',
        'Mark the mapping as "Verified" once validated by your technical team.',
        'Use "Generate FHIR Export" to preview a sample FHIR Bundle JSON.',
      ]} />
    </HelpSection>

    <HelpSection title="Key FHIR Resources for Medical Devices">
      <div className="space-y-2">
        <InfoCard title="Device" description="Describes the medical device itself — UDI-DI, manufacturer, model. Maps to your device registry data." />
        <InfoCard title="Observation" description="Measurements and readings (weight, blood pressure, glucose). Most device data maps here." />
        <InfoCard title="DiagnosticReport" description="Structured reports from device outputs (e.g., ECG interpretation, imaging results)." />
        <InfoCard title="Procedure" description="Therapy sessions, treatment cycles, surgical procedures performed with the device." />
        <InfoCard title="DeviceUseStatement" description="Records of device usage — when, how long, by whom." />
        <InfoCard title="AdverseEvent" description="Device-related incidents and adverse events. Critical for pharmacovigilance integration." />
      </div>
    </HelpSection>

    <HelpSection title="Mapping Completeness">
      <p className="text-sm text-muted-foreground">
        The progress bar shows what percentage of your internal fields have been mapped. Aim for <strong>100% 
        mapped</strong> and <strong>100% verified</strong>. Unmapped fields represent data that cannot be 
        shared in the EEHRxF format — which could block cross-border data access requests.
      </p>
    </HelpSection>

    <HelpSection title="Auditor Expectations">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>• <strong>Coverage:</strong> All health-relevant fields should be mapped. Non-health fields (internal IDs, timestamps) can be excluded with justification.</p>
        <p>• <strong>Correctness:</strong> Mappings should use correct FHIR resource types and field paths. Incorrect mappings can lead to data misinterpretation.</p>
        <p>• <strong>Transformation transparency:</strong> If data conversion is needed (units, coding systems), document it in the transformation notes.</p>
        <p>• <strong>Validation:</strong> The generated FHIR Bundle should pass standard FHIR validation. Use the preview to check structure.</p>
      </div>
    </HelpSection>

    <TipCard>
      If you're unsure which FHIR resource to use, start with "Observation" for any measurement data and 
      "Device" for device identification. These two cover 80% of typical medical device data.
    </TipCard>
  </div>
);

// ─── Tab 3: Secondary Use ───

export const EHDSSecondaryUseHelp: React.FC = () => (
  <div className="space-y-6">
    <div className="flex flex-wrap gap-2 mb-3">
      <ArticleBadge article="Art. 33–35, Art. 45–49" />
      <ArticleBadge article="Chapter IV" />
      <TimelineBadge date="HDAB Requests: 2029+" status="future" />
    </div>

    <p className="text-sm text-muted-foreground">
      The Secondary Use module helps you manage <strong>incoming data access requests</strong> from Health Data 
      Access Bodies (HDABs). Under Chapter IV of the EHDS, researchers, health authorities, and public health 
      organizations can legally request access to your anonymized or pseudonymized health data — and you must 
      respond within defined timelines.
    </p>

    <TimelineCallout title="When Does This Apply?">
      <p>HDABs will begin operating from <strong>2029 onwards</strong> (phased by member state). However, you 
      should establish your governance workflow <strong>now</strong>. When the first request arrives, you need 
      a documented process for evaluating it, checking trade secrets, and preparing data in a Secure Processing 
      Environment (SPE). Ad-hoc responses will fail audit.</p>
    </TimelineCallout>

    <HelpSection title="What Is an HDAB?">
      <p className="text-sm text-muted-foreground">
        A <strong>Health Data Access Body</strong> is a national authority (one per EU member state) that 
        mediates between data users (researchers, regulators) and data holders (you). Think of it as a 
        "data court" — researchers apply to the HDAB, the HDAB evaluates the request, and if approved, 
        issues a <strong>data permit</strong> requiring you to provide the data.
      </p>
    </HelpSection>

    <HelpSection title="The Data Permit Workflow">
      <StepList steps={[
        'A researcher submits a data access application to their national HDAB.',
        'The HDAB evaluates the application (purpose, legal basis, data minimization).',
        'If approved, the HDAB issues a Data Permit and notifies you (the Data Holder).',
        'You receive the permit in Xyreg — create a new permit entry with the HDAB reference number.',
        'Review the request: which datasets? What purpose? Is trade secret protection needed?',
        'If trade secrets are involved, your PRRC must sign off on the review (Article 35).',
        'Prepare the data: apply anonymization/pseudonymization as required by the permit.',
        'Release the data to the Secure Processing Environment (SPE) specified in the permit.',
        'Update the permit status to "Data Released" and archive the compliance evidence.',
      ]} />
    </HelpSection>

    <HelpSection title="Trade Secret Protection (Article 35)">
      <p className="text-sm text-muted-foreground">
        You have the right to <strong>flag data elements as trade secrets</strong>. If a permit requests data 
        that contains proprietary algorithms, manufacturing parameters, or commercially sensitive information, 
        you can request the HDAB to apply additional protections or exclude those elements.
      </p>
      <InfoCard 
        title="PRRC Sign-Off Required" 
        description="Your Person Responsible for Regulatory Compliance (PRRC) must review and sign off on any trade secret determination. This is documented in the permit record and must be available for audit." 
      />
    </HelpSection>

    <HelpSection title="Secure Processing Environments (SPEs)">
      <p className="text-sm text-muted-foreground">
        Data released under a permit must be accessed through a <strong>Secure Processing Environment</strong> — 
        a controlled computing environment where researchers can analyze data without downloading or copying it. 
        You don't need to build an SPE; the HDAB or an authorized service provider manages it. Your job is to 
        deliver the data to the designated SPE.
      </p>
    </HelpSection>

    <HelpSection title="Permit Statuses">
      <div className="space-y-2">
        <InfoCard title="Received" description="You've been notified of a new permit. Start your internal review." />
        <InfoCard title="Under Review" description="Your team is evaluating the request — checking datasets, trade secrets, anonymization needs." />
        <InfoCard title="Approved" description="Internal review complete. Data preparation in progress." />
        <InfoCard title="Rejected" description="You've formally objected to the permit (with documented justification to the HDAB)." />
        <InfoCard title="Data Released" description="Data has been delivered to the SPE. Permit fulfilled." />
      </div>
    </HelpSection>

    <HelpSection title="Auditor Expectations">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>• <strong>Process documentation:</strong> You must have a documented SOP for handling HDAB requests.</p>
        <p>• <strong>Response timelines:</strong> The EHDS specifies maximum response times. Track these in the permit record.</p>
        <p>• <strong>Trade secret log:</strong> Every trade secret claim must be documented with justification.</p>
        <p>• <strong>Data preparation evidence:</strong> Show that anonymization/pseudonymization was applied correctly before release.</p>
        <p>• <strong>SPE verification:</strong> Confirm the SPE meets EHDS security requirements before releasing data.</p>
      </div>
    </HelpSection>

    <WarningCard>
      You <strong>cannot refuse a valid data permit</strong> without documented justification. Blanket refusals 
      are non-compliant. If you believe a request is overly broad or threatens trade secrets, you must engage 
      with the HDAB through the formal objection process.
    </WarningCard>

    <TipCard>
      Even before HDABs are operational, create a "dry run" permit to test your internal workflow. 
      This ensures your team knows the process when real requests arrive.
    </TipCard>
  </div>
);

// ─── Tab 4: Anonymization Lab ───

export const EHDSAnonymizationHelp: React.FC = () => (
  <div className="space-y-6">
    <div className="flex flex-wrap gap-2 mb-3">
      <ArticleBadge article="Art. 44, Art. 49" />
      <ArticleBadge article="GDPR Art. 4(5)" />
      <TimelineBadge date="Required for: Data Releases (2029+)" status="future" />
    </div>

    <p className="text-sm text-muted-foreground">
      The Anonymization Lab helps you define <strong>how to strip personally identifiable information (PII)</strong> 
      from your datasets before they are shared under secondary use permits. It provides templates, tracks which 
      fields are classified as PII, and calculates a Privacy Score to gauge the strength of your de-identification.
    </p>

    <TimelineCallout title="When Does This Apply?">
      <p>Anonymization or pseudonymization is required <strong>before any secondary data release</strong> (2029+). 
      However, GDPR already requires this for any data sharing outside the original purpose. Setting up your 
      anonymization profiles now ensures you're ready for both GDPR and EHDS obligations.</p>
    </TimelineCallout>

    <HelpSection title="Anonymization vs. Pseudonymization">
      <div className="space-y-2">
        <InfoCard 
          title="Anonymization (irreversible)" 
          description="All identifying information is permanently removed. The data can never be re-linked to an individual. Anonymized data is no longer 'personal data' under GDPR. Use this for broad secondary use (research, public health statistics)." 
        />
        <InfoCard 
          title="Pseudonymization (reversible)" 
          description="Identifying information is replaced with artificial identifiers (pseudonyms). The data CAN be re-linked using a separate key. Still counts as personal data under GDPR. Use this when the data user needs to link records over time or across datasets." 
        />
      </div>
      <WarningCard>
        The HDAB's data permit will specify whether anonymization or pseudonymization is required. 
        You don't get to choose — the permit dictates the method.
      </WarningCard>
    </HelpSection>

    <HelpSection title="Common PII Fields to Strip">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>• <strong>Direct identifiers:</strong> Name, date of birth, national ID number, email, phone</p>
        <p>• <strong>Quasi-identifiers:</strong> Age (use age ranges), zip code (use region), rare conditions</p>
        <p>• <strong>Device identifiers:</strong> Device serial numbers linked to patients (use pseudonyms)</p>
        <p>• <strong>Temporal data:</strong> Exact timestamps (generalize to date or week)</p>
        <p>• <strong>Location data:</strong> GPS coordinates, hospital names (generalize to region)</p>
        <p>• <strong>Free text:</strong> Clinical notes, comments (apply NLP-based redaction or exclude)</p>
      </div>
    </HelpSection>

    <HelpSection title="How to Create an Anonymization Profile">
      <StepList steps={[
        'Select a dataset from your Dataset Library.',
        'Xyreg lists all fields in the dataset. Toggle each field as "PII" or "Non-PII."',
        'For each PII field, choose the de-identification method: remove, generalize, pseudonymize, or encrypt.',
        'Select a template (GDPR Standard, EHDS Standard, or Custom) as a starting point.',
        'Review the Privacy Score — it calculates based on the ratio of PII fields stripped vs. total fields, weighted by re-identification risk.',
        'Save the profile. You can create multiple profiles per dataset (e.g., one for anonymization, one for pseudonymization).',
        'When a secondary use permit requires data release, apply the appropriate profile.',
      ]} />
    </HelpSection>

    <HelpSection title="Privacy Score Methodology">
      <p className="text-sm text-muted-foreground">
        The Privacy Score (0–100) is a simplified measure of de-identification strength:
      </p>
      <div className="space-y-2 mt-2">
        <InfoCard title="90–100: Strong" description="All direct identifiers removed; quasi-identifiers generalized. Low re-identification risk. Suitable for broad secondary use." />
        <InfoCard title="70–89: Moderate" description="Direct identifiers removed but some quasi-identifiers remain specific. Acceptable for controlled SPE access." />
        <InfoCard title="50–69: Weak" description="Significant re-identification risk. Additional de-identification recommended before release." />
        <InfoCard title="Below 50: Insufficient" description="Too much PII remains. Do NOT release data with this profile. Revisit field-level stripping." />
      </div>
    </HelpSection>

    <HelpSection title="Templates">
      <div className="space-y-2">
        <InfoCard title="GDPR Standard" description="Strips all 18 GDPR-defined personal data categories. Conservative baseline suitable for most use cases." />
        <InfoCard title="EHDS Standard" description="Extends GDPR template with health-specific fields (rare diseases, genetic markers, device serial numbers linked to patients)." />
        <InfoCard title="Custom" description="Start from scratch and define your own PII field list. Use when your data has domain-specific identifiers not covered by standard templates." />
      </div>
    </HelpSection>

    <HelpSection title="Auditor Expectations">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>• <strong>Profile documentation:</strong> Every anonymization profile must be documented and versioned.</p>
        <p>• <strong>Method justification:</strong> Explain why you chose anonymization vs. pseudonymization for each profile.</p>
        <p>• <strong>Re-identification risk assessment:</strong> The Privacy Score provides a baseline, but auditors may ask for a formal risk assessment.</p>
        <p>• <strong>Audit trail:</strong> Every time a profile is applied to release data, it must be logged with timestamp, applied_by, and permit reference.</p>
      </div>
    </HelpSection>

    <TipCard>
      Start with the "EHDS Standard" template — it covers 90% of medical device data scenarios. 
      Customize only for fields specific to your device's data model.
    </TipCard>
  </div>
);

// ─── Tab 5: Self-Declaration ───

export const EHDSSelfDeclarationHelp: React.FC = () => (
  <div className="space-y-6">
    <div className="flex flex-wrap gap-2 mb-3">
      <ArticleBadge article="Annex II" />
      <ArticleBadge article="Art. 26" />
      <TimelineBadge date="At Market Placement" status="upcoming" />
    </div>

    <p className="text-sm text-muted-foreground">
      The Self-Declaration module helps you complete the <strong>EHDS Annex II conformity checklist</strong> 
      and generate an EU Declaration of Conformity for data compliance. This is similar to what you already do 
      for CE marking (MDR Declaration of Conformity), but specifically for your device's data-sharing obligations 
      under the EHDS.
    </p>

    <TimelineCallout title="When Does This Apply?">
      <p>The self-declaration is required <strong>at the time of market placement</strong> for any EHR system 
      or wellness application that falls under the EHDS scope. For medical devices that generate health data, 
      the timeline aligns with the secondary use framework (<strong>2029+</strong>). However, the Commission 
      may publish implementing acts earlier — monitor the Official Journal.</p>
    </TimelineCallout>

    <HelpSection title="What Is Annex II?">
      <p className="text-sm text-muted-foreground">
        Annex II of the EHDS Regulation defines the <strong>essential requirements for data interoperability</strong>. 
        It's a checklist that covers:
      </p>
      <div className="space-y-2 mt-2 text-sm text-muted-foreground">
        <p>• <strong>Data format compliance:</strong> Does your device output data in EEHRxF-compatible format?</p>
        <p>• <strong>Interoperability standards:</strong> Do you support HL7 FHIR R4 or later?</p>
        <p>• <strong>Data portability:</strong> Can patients export their data in a structured, machine-readable format?</p>
        <p>• <strong>Security requirements:</strong> Does your device meet the cybersecurity requirements for health data?</p>
        <p>• <strong>Logging & transparency:</strong> Does your device log data access events?</p>
        <p>• <strong>Labelling:</strong> Does your device carry the EHDS conformity label (once defined by implementing acts)?</p>
      </div>
    </HelpSection>

    <HelpSection title="How It Differs from CE Marking">
      <div className="space-y-2">
        <InfoCard 
          title="CE Marking (MDR)" 
          description="Covers safety and performance of the device as a medical device. Requires Notified Body assessment for higher-risk classes. You already do this." 
        />
        <InfoCard 
          title="EHDS Self-Declaration" 
          description="Covers data interoperability and sharing obligations. Self-declared by the manufacturer (no Notified Body). Think of it as a 'data CE mark.'" 
        />
      </div>
      <TipCard>
        The two declarations are complementary, not mutually exclusive. You need both: CE marking for device safety, 
        EHDS declaration for data compliance.
      </TipCard>
    </HelpSection>

    <HelpSection title="How to Complete the Self-Declaration">
      <StepList steps={[
        'Review each Annex II checklist item. For each requirement, select your compliance status (Compliant / Partially Compliant / Non-Compliant / Not Applicable).',
        'For each item marked "Compliant," provide a brief justification or link to supporting evidence.',
        'For "Partially Compliant" items, document the gap and your remediation plan with timeline.',
        'For "Not Applicable" items, provide a clear justification (e.g., "Device does not generate patient-facing data").',
        'Once all items are addressed, the overall status will update automatically.',
        'When status is "Compliant," use "Generate Declaration" to create the formal PDF document.',
        'Have the declaration signed by your authorized representative (typically the PRRC).',
        'Attach the declaration to your Technical File alongside your MDR Declaration of Conformity.',
      ]} />
    </HelpSection>

    <HelpSection title="Company-Wide vs. Per-Product">
      <p className="text-sm text-muted-foreground">
        You can create declarations at two levels:
      </p>
      <div className="space-y-2 mt-2">
        <InfoCard 
          title="Company-Wide" 
          description="Covers your organization's general EHDS compliance posture (data governance, security infrastructure, HDAB response processes). Create one for the company." 
        />
        <InfoCard 
          title="Per-Product" 
          description="Covers product-specific data interoperability (EEHRxF mapping, data export capabilities, specific dataset compliance). Create one per device that generates health data." 
        />
      </div>
    </HelpSection>

    <HelpSection title="Auditor Expectations">
      <div className="space-y-2 text-sm text-muted-foreground">
        <p>• <strong>Completeness:</strong> Every Annex II requirement must be addressed. "Not Applicable" requires justification.</p>
        <p>• <strong>Evidence linking:</strong> Each compliance claim should reference supporting evidence (dataset catalog, FHIR mapping, anonymization profile).</p>
        <p>• <strong>Currency:</strong> The declaration must reflect the current device version. Update it with each major release.</p>
        <p>• <strong>Signature:</strong> The declaration must be signed by an authorized person. Unsigned declarations are invalid.</p>
        <p>• <strong>Accessibility:</strong> The declaration must be available to market surveillance authorities on request.</p>
      </div>
    </HelpSection>

    <WarningCard>
      The European Commission will publish implementing acts that define the exact Annex II checklist format. 
      Xyreg will update this module when the implementing acts are finalized. For now, the checklist covers 
      the essential requirements as stated in the Regulation text.
    </WarningCard>

    <TipCard>
      Don't wait for the implementing acts. Complete what you can now using the current checklist. 
      When the final format is published, you'll only need to align — not start from scratch.
    </TipCard>
  </div>
);
