/**
 * Helix OS Plan Menu Access Configuration
 *
 * This file defines which features are enabled for the Helix OS (paid) plan.
 * Helix OS has FULL ACCESS to all features.
 *
 * All menu_access keys are set to true for complete platform access.
 */

import {
  MISSION_CONTROL_MENU_ACCESS,
  PORTFOLIO_MENU_ACCESS,
  DEVICES_MENU_ACCESS,
  DRAFT_STUDIO_MENU_ACCESS,
} from './menuAccessKeys';

/**
 * Helix OS Plan Menu Access Configuration
 * true = enabled (ALL features enabled for Helix OS)
 */
export const HELIX_OS_MENU_ACCESS: Record<string, boolean | Record<string, number>> = {
  // ==================== MISSION CONTROL ====================
  [MISSION_CONTROL_MENU_ACCESS.MISSION_CONTROL]: true,
  [MISSION_CONTROL_MENU_ACCESS.CLIENT_COMPASS]: true,

  // ==================== PORTFOLIO (COMPANY DASHBOARD) ====================
  [PORTFOLIO_MENU_ACCESS.DASHBOARD]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_STRATEGIC_BLUEPRINT]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_BUSINESS_CANVAS]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_FEASIBILITY_STUDIES]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_MARKET_ANALYSIS]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_COMMERCIAL_PERFORMANCE]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_VARIANCE_ANALYSIS]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_PRICING_STRATEGY]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_INVESTORS]: true,
  [PORTFOLIO_MENU_ACCESS.COMMERCIAL_IP_PORTFOLIO]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_GENESIS]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_SUNBURST]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_PHASES_CHART]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_CARDS]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_PHASES]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_TIMELINE]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_LIST]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_RELATIONSHIPS]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_HIERARCHY]: true,
  [PORTFOLIO_MENU_ACCESS.DEVICE_PORTFOLIO_BUNDLES]: true,
  [PORTFOLIO_MENU_ACCESS.MILESTONES]: true,
  [PORTFOLIO_MENU_ACCESS.COMPLIANCE_INSTANCES]: true,
  [PORTFOLIO_MENU_ACCESS.COMPLIANCE_DOCUMENTS]: true,
  [PORTFOLIO_MENU_ACCESS.COMPLIANCE_GAP_ANALYSIS]: true,
  [PORTFOLIO_MENU_ACCESS.COMPLIANCE_ACTIVITIES]: true,
  [PORTFOLIO_MENU_ACCESS.COMPLIANCE_AUDITS]: true,
  [PORTFOLIO_MENU_ACCESS.OPERATIONS]: true,
  [PORTFOLIO_MENU_ACCESS.OPERATIONS_BUDGET]: true,
  [PORTFOLIO_MENU_ACCESS.OPERATIONS_SUPPLIERS]: true,
  [PORTFOLIO_MENU_ACCESS.PMS]: true,
  [PORTFOLIO_MENU_ACCESS.TRAINING]: true,
  [PORTFOLIO_MENU_ACCESS.COMMUNICATIONS]: true,
  [PORTFOLIO_MENU_ACCESS.AUDIT_LOG]: true,

  // ==================== DEVICES (PRODUCT LEVEL) ====================
  [DEVICES_MENU_ACCESS.DASHBOARD]: true,

  // Business Case - All enabled
  [DEVICES_MENU_ACCESS.BUSINESS_CASE]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_VIABILITY]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_VENTURE]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_CANVAS]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_TEAM]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_MARKET_SIZING]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_COMPETITION]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_RNPV]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_REIMBURSEMENT]: true,
  [DEVICES_MENU_ACCESS.BUSINESS_CASE_PRICING]: true,

  // Device Definition - All enabled
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_OVERVIEW]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_PURPOSE]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_GENERAL]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_IDENTIFICATION]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_REGULATORY]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_MARKETS]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_BUNDLES]: true,
  [DEVICES_MENU_ACCESS.DEVICE_DEFINITION_AUDIT_LOG]: true,

  // Design & Risk Controls - All enabled for Helix OS
  [DEVICES_MENU_ACCESS.DESIGN_RISK]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_REQUIREMENTS]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_REQUIREMENTS_USER_NEEDS]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_REQUIREMENTS_SYSTEM]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_REQUIREMENTS_SOFTWARE]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_REQUIREMENTS_HARDWARE]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_ARCHITECTURE]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_MANAGEMENT]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_VV]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_VV_PLAN]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_VV_TEST_CASES]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_VV_TEST_EXECUTION]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_VV_DEFECTS]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_VV_REPORTS]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_VV_AI_ASSURANCE]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_TRACEABILITY]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_TRACEABILITY_MATRIX]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_TRACEABILITY_GAPS]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_TRACEABILITY_IMPACT]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_TRACEABILITY_SETTINGS]: true,
  [DEVICES_MENU_ACCESS.DESIGN_RISK_UEF]: true,

  // Clinical Trials - Enabled
  [DEVICES_MENU_ACCESS.CLINICAL_TRIALS]: true,

  // Milestones - Enabled
  [DEVICES_MENU_ACCESS.MILESTONES]: true,

  // Compliance Instances - All enabled
  [DEVICES_MENU_ACCESS.COMPLIANCE_INSTANCES]: true,
  [DEVICES_MENU_ACCESS.COMPLIANCE_DOCUMENTS]: true,
  [DEVICES_MENU_ACCESS.COMPLIANCE_GAP_ANALYSIS]: true,
  [DEVICES_MENU_ACCESS.COMPLIANCE_ACTIVITIES]: true,
  [DEVICES_MENU_ACCESS.COMPLIANCE_AUDITS]: true,

  // Post-Market Surveillance - Enabled
  [DEVICES_MENU_ACCESS.PMS]: true,

  // User Access - Enabled
  [DEVICES_MENU_ACCESS.USER_ACCESS]: true,

  // ==================== DOCUMENT STUDIO ====================
  [DRAFT_STUDIO_MENU_ACCESS.DOCUMENT_STUDIO]: true,

  // ==================== FEATURE LIMITS ====================
  // Helix OS has higher limits
  '_feature_limits': {
    'devices.device-definition.target-markets': 100,
    'max_devices': 100,
  },
};

/**
 * Helix OS Plan Features (for display purposes)
 */
export const HELIX_OS_FEATURES = [
  '1 Device (expandable)',
  '3 Module slots',
  '500 AI credits/mo',
  'Full QMS tools',
  'Priority support',
];

/**
 * SQL to update the Helix OS plan in the database
 * Run this in Supabase SQL editor to update the plan
 */
export const HELIX_OS_PLAN_SQL = `
-- Update Helix OS plan menu_access in new_pricing_plans table
UPDATE new_pricing_plans
SET menu_access = '${JSON.stringify(HELIX_OS_MENU_ACCESS)}'::jsonb,
    updated_at = NOW()
WHERE name = 'core' OR display_name = 'Helix OS';
`;
