import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { trackTokenUsage, extractLovableAIUsage } from "../_shared/token-tracking.ts";

declare const EdgeRuntime: { waitUntil(promise: Promise<unknown>): void };

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { currentContent, previousContent, versionName, companyId } = await req.json();
    
    if (!currentContent || !previousContent) {
      return new Response(
        JSON.stringify({ error: "Missing required content for comparison" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const systemPrompt = `You are an expert document analyst specializing in version control and change management for medical device documentation. Generate a concise comparison summary between two document versions.

CRITICAL FORMATTING INSTRUCTIONS:
- ALWAYS format your response as bulleted points using the "•" bullet character
- Start EVERY point with "•" followed by a space
- Each point should be on a new line
- Use clear, concise language
- Focus on the most significant changes
- Organize by change type (additions, deletions, modifications)
- If no changes, still format as bullets

Example format:
• First key change or observation
• Second key change or observation
• Third key change or observation`;

    const userPrompt = `Compare these two document versions and provide a brief summary:

CURRENT VERSION:
${currentContent}

PREVIOUS VERSION (${versionName}):
${previousContent}

Provide a concise comparison highlighting:
• Key additions
• Important deletions  
• Significant modifications
• Overall impact of changes

Remember: Format EVERY line as a bullet point starting with "•"`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
        max_tokens: 1000,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limits exceeded. Please try again later." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "Payment required. Please add credits to your Lovable AI workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      return new Response(
        JSON.stringify({ error: "AI gateway error" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("No content generated by AI");
    }

    // Track token usage in background if company_id provided
    if (companyId) {
      const usage = extractLovableAIUsage(data);
      if (usage) {
        EdgeRuntime.waitUntil(
          trackTokenUsage(companyId, 'gemini', usage)
        );
      }
    }

    return new Response(
      JSON.stringify({ success: true, content }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error) {
    console.error("Error in document summary comparison:", error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : "Unknown error occurred" 
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
