-- Add comprehensive medical device document templates
-- Simple insert approach for existing phases

-- First, let's add some sample documents to the first concept phase we find
INSERT INTO phase_assigned_documents (phase_id, name, document_type, document_scope, status, tech_applicability, description)
SELECT 
    p.id,
    doc.name,
    doc.document_type,
    'company_template',
    'template',
    doc.tech_applicability,
    doc.description
FROM phases p
CROSS JOIN (VALUES 
    ('Business Case / Project Charter', 'Standard', 'All device types', 'Project rationale, objectives, business justification.'),
    ('Concept Brief', 'Standard', 'All device types', 'Defines initial concept, intended use, key features, target market, and regulatory strategy.'),
    ('User Needs Overview', 'Standard', 'All device types', 'Consolidated user requirements.'),
    ('Early Competitive Landscape Summary', 'Standard', 'All device types', 'Market competitor analysis and positioning.'),
    ('Draft Risk Management Plan', 'Quality', 'All device types', 'Preliminary document outlining approach to managing risks.'),
    ('Feasibility Study Report (with risk inputs)', 'Standard', 'All device types', 'Documentation assessing device feasibility with an emphasis on initial risk assessment.'),
    ('High-Level Architecture / Concept Diagram', 'Technical', 'All device types', 'Visual diagrams outlining the device''s overall system architecture and components.'),
    ('Initial Hazard Log / FMEA Entries', 'Quality', 'All device types', 'Early documentation of identified hazards and failure modes for risk management.'),
    ('Intellectual Property (IP) Review', 'Standard', 'All device types', 'Evaluation of intellectual property considerations and protection strategies.'),
    ('Preliminary Hazard Analysis (PHA)', 'Quality', 'All device types', 'Early-stage analysis identifying potential hazards and their impacts.'),
    ('Preliminary Market Analysis', 'Standard', 'All device types', 'Early assessment of market potential, size, and dynamics.'),
    ('Regulatory Strategy Outline', 'Regulatory', 'All device types', 'Document outlining the regulatory approval strategy and pathways.'),
    ('Resource & Budget Feasibility Study', 'Standard', 'All device types', 'Analysis of resource requirements and budget considerations.'),
    ('Quality Management Plan', 'Quality', 'All device types', 'Plan detailing overall quality management strategy and processes.'),
    ('Internal Audit Reports', 'Quality', 'All device types', 'Reports documenting the findings of internal quality system audits.'),
    ('Management Review Minutes', 'Quality', 'All device types', 'Records documenting management reviews of the quality system.'),
    ('Periodic Audit / Review Schedule', 'Quality', 'All device types', 'Schedule documenting periodic internal and external audits.'),
    ('Traceability Matrices (Req → Design → Verif → Valid → Risk)', 'Quality', 'All device types', 'Documentation demonstrating traceability across requirements, design, verification, validation, and risk management.'),
    ('Design & Development Plan', 'Standard', 'All device types', 'Device development processes, resources, timelines.'),
    ('Verification Test Reports (functional, EMC, biocomp., sterility, SW)', 'Quality', 'All device types', 'Documentation of results from various verification tests.'),
    ('Biocompatibility Requirements', 'Clinical', 'Implantable devices', 'Biocompatibility testing and evaluation.'),
    ('Calibration Certificates for Test Equipment', 'Quality', 'All device types', 'Calibration documentation for test equipment.'),
    ('Design Review Records', 'Quality', 'All device types', 'Documentation of formal design reviews to ensure compliance and effectiveness.'),
    ('EMC Requirements (IEC 60601-1-2)', 'Regulatory', 'Electronic devices', 'Documentation ensuring compliance with electromagnetic compatibility standards.'),
    ('Environmental & Sterilization Specs', 'Technical', 'Sterile devices', 'Specifications and procedures for environmental testing and sterilization.'),
    ('Packaging Design Drawings', 'Technical', 'All device types', 'Technical drawings of packaging components.'),
    ('Packaging Validation Reports', 'Quality', 'All device types', 'Reports documenting validation of packaging processes.'),
    ('Pre-Clinical / Pre-Study Protocols', 'Clinical', 'All device types', 'Protocols for pre-clinical testing to assess device performance and safety.'),
    ('Process Validation Protocols & Reports (sterility, shelf-life)', 'Quality', 'Sterile devices', 'Documentation of validation protocols and results for sterility and shelf-life.'),
    ('Risk Control Implementation Records', 'Quality', 'All device types', 'Documentation detailing implementation of risk control measures.'),
    ('Software Architecture & Code Documentation', 'Technical', 'Software devices', 'Documentation detailing the software architecture and source code.'),
    ('Software Lifecycle Documentation (IEC 62304)', 'Technical', 'Software devices', 'Comprehensive documentation of the software development lifecycle.'),
    ('Software Validation Reports (IQ/OQ/PQ)', 'Technical', 'Software devices', 'Reports documenting software validation activities and outcomes.'),
    ('Sterilization & Shelf-Life Validation Summaries', 'Quality', 'Sterile devices', 'Reports summarizing validation of sterilization processes and product shelf-life.'),
    ('Test Method Development Plan', 'Quality', 'All device types', 'Plan outlining methods for developing test procedures.'),
    ('Test Method Validation Reports', 'Quality', 'All device types', 'Reports documenting validation of testing methods.'),
    ('Updated Hazard Log / FMEA with Controls', 'Quality', 'All device types', 'Updated documentation of identified hazards, risks, and implemented controls.'),
    ('Updated Traceability Matrix w/ Verification Links', 'Quality', 'All device types', 'Document linking design inputs and outputs directly to verification activities.'),
    ('Verification Master Plan', 'Quality', 'All device types', 'Plan outlining the strategy and procedures for verification activities.'),
    ('Verification Protocols & Acceptance Criteria', 'Quality', 'All device types', 'Detailed procedures and criteria for verifying design and performance specifications.'),
    ('CE Technical File & EU Declaration of Conformity', 'Regulatory', 'EU market devices', 'EU market entry technical and conformity documentation.'),
    ('Technical File / Design Dossier / Device Master Record', 'Regulatory', 'All device types', 'Comprehensive compilation of documentation required for regulatory submissions and production.'),
    ('510(k) Submission / PMA Package', 'Regulatory', 'FDA regulated devices', 'FDA market submission documentation.'),
    ('ANVISA Registro', 'Regulatory', 'Brazil market devices', 'Brazilian regulatory approval documentation.'),
    ('ARTG Inclusion', 'Regulatory', 'Australia market devices', 'Australian market regulatory documentation.'),
    ('CAPA Procedure (Post-Market)', 'Quality', 'All device types', 'Procedures for managing corrective and preventive actions.'),
    ('CAPA Records & Effectiveness Checks', 'Quality', 'All device types', 'Documentation of CAPA actions and effectiveness.'),
    ('CDSCO Device Registration', 'Regulatory', 'India market devices', 'Documentation for Indian regulatory approval.'),
    ('Clinical Evaluation Plan & Protocols', 'Clinical', 'All device types', 'Clinical evaluation strategy and methods.'),
    ('Clinical Investigation / Trial Protocols & CRFs', 'Clinical', 'All device types', 'Clinical trial documentation.'),
    ('CN Registration Certificate application', 'Regulatory', 'China market devices', 'Regulatory documentation for China market approval.'),
    ('Design Validation Reports (simulated & actual use)', 'Quality', 'All device types', 'Reports documenting validation tests under real and simulated conditions.'),
    ('Electrical Schematics & PCB Layouts', 'Technical', 'Electronic devices', 'Detailed documentation of electrical designs and printed circuit board layouts.'),
    ('Executive Sign-Off on Risk Acceptance', 'Quality', 'All device types', 'Formal approval from management accepting residual risks identified.'),
    ('Field Safety Corrective Action (FSCA) Reports', 'Quality', 'All device types', 'Reports documenting corrective actions taken in response to identified safety issues post-market.'),
    ('Final Design Review Minutes', 'Quality', 'All device types', 'Formal records documenting final design review and approval.'),
    ('Human Factors Use-Specifications', 'Clinical', 'All device types', 'Documentation detailing user interface requirements and usability considerations.'),
    ('Installation, Operation & Servicing Instructions Drafts', 'Technical', 'All device types', 'Preliminary user manuals for installation, operation, and servicing of the device.'),
    ('KR Marketing Authorization', 'Regulatory', 'Korea market devices', 'Regulatory documentation required for device approval in the South Korean market.'),
    ('Labeling Drafts & UDI Assignments', 'Regulatory', 'All device types', 'Preliminary labeling and UDI documentation drafts.'),
    ('Labeling & IFU Final', 'Regulatory', 'All device types', 'Final versions of labels and Instructions for Use for the device.'),
    ('Manufacturing Process Flowcharts & Work Instructions', 'Quality', 'All device types', 'Documentation detailing manufacturing processes and procedures.'),
    ('Medical Device License (MDL) application', 'Regulatory', 'Canada market devices', 'Regulatory submission documentation required for Canadian market approval.'),
    ('Periodic Safety Update Reports (PSUR/PBRER)', 'Regulatory', 'All device types', 'Reports summarizing ongoing safety surveillance data.'),
    ('Post-Market Clinical Follow-Up (PMCF) Plan', 'Clinical', 'All device types', 'Plan outlining post-market clinical data collection methods.'),
    ('Post-Market Risk Reassessment Updates', 'Quality', 'All device types', 'Updates to risk assessments based on post-market data.'),
    ('Post-Market Surveillance (PMS) Plan', 'Quality', 'All device types', 'Strategy and procedures for ongoing post-market device surveillance.'),
    ('Project Schedule / Gantt Chart', 'Standard', 'All device types', 'Detailed timeline for device development and launch milestones.'),
    ('Regulatory & Standards Mapping Matrix', 'Regulatory', 'All device types', 'Matrix aligning product features and documentation with relevant standards and regulations.'),
    ('Regulatory Submission Roadmap', 'Regulatory', 'All device types', 'Timeline and strategy outlining regulatory submission milestones.'),
    ('Risk Management Plan (Final)', 'Quality', 'All device types', 'Comprehensive plan outlining risk management strategies and processes.'),
    ('Risk/Benefit Analysis & Residual Risk Summary', 'Quality', 'All device types', 'Analysis comparing device risks against clinical benefits.'),
    ('Shonin / Ninsho dossier', 'Regulatory', 'Japan market devices', 'Regulatory submission documentation required for device approval in Japan.'),
    ('Software Requirements Specification (SRS)', 'Technical', 'Software devices', 'Document outlining detailed software requirements.'),
    ('Stakeholder Requirements Specification', 'Design', 'All device types', 'Documentation detailing requirements from stakeholders.'),
    ('Supplier / Contract Manufacturer Agreements', 'Quality', 'All device types', 'Formal agreements defining responsibilities and requirements with suppliers.'),
    ('Supplier Qualification Records', 'Quality', 'All device types', 'Documentation verifying qualifications and compliance of suppliers.'),
    ('Supplier Selection & Qualification Plan', 'Quality', 'All device types', 'Plan detailing processes for selecting and qualifying suppliers.'),
    ('Usability Engineering File (UEF)', 'Clinical', 'All device types', 'Documentation detailing usability assessments, user interface design, and risk management related to user interactions.'),
    ('Use Environment & Maintenance Profiles', 'Technical', 'All device types', 'Documentation outlining intended device usage environments and required maintenance activities.'),
    ('User Needs Specification (UNS)', 'Design', 'All device types', 'Detailed specification of user needs and intended use requirements.'),
    ('Validation Master Plan (Design, Clinical, Usability)', 'Clinical', 'All device types', 'Comprehensive plan detailing all validation activities for design, clinical, and usability aspects.'),
    ('Vigilance & Adverse Event Reporting Procedure', 'Regulatory', 'All device types', 'Defined procedures for reporting vigilance and adverse events.'),
    ('Vigilance Reports (MDR, MedWatch, etc.)', 'Regulatory', 'All device types', 'Reports documenting adverse events and vigilance activities submitted to regulatory authorities.'),
    ('Detailed CAD Drawings & BOM', 'Technical', 'All device types', 'Technical drawings and Bill of Materials detailing device specifications.'),
    ('Device History File (DHF) Index', 'Quality', 'All device types', 'Index documenting all development records maintained for regulatory compliance.')
) AS doc(name, document_type, tech_applicability, description)
WHERE p.name ILIKE '%Concept%' OR p.name ILIKE '%Feasibility%'
LIMIT 100;