-- Continue with remaining ISO 13485 template items (Clauses 6, 7, 8) - completing the 65-item structure
DO $$
DECLARE
    template_uuid UUID;
BEGIN
    -- Find the ISO 13485 template
    SELECT id INTO template_uuid 
    FROM gap_analysis_templates 
    WHERE framework = 'ISO 13485:2016' OR name ILIKE '%ISO 13485%'
    LIMIT 1;
    
    -- If template exists, continue inserting remaining items
    IF template_uuid IS NOT NULL THEN
        
        -- Clause 6: Resource Management - 15 items (positions 18-32)
        INSERT INTO gap_template_items (
            template_id, item_number, requirement_text, category, priority, clause_number, 
            clause_description, question_number, evidence_method, audit_guidance, sort_order
        ) VALUES 
        (template_uuid, '6.1.1', 'Does the organization determine and provide adequate resources to implement the QMS and meet regulatory and customer requirements?', 'verification', 'medium', '6', 'Resource Management - This clause covers the people, infrastructure, and work environment needed to produce safe medical devices.', '6.1', 'Management review minutes and resource allocation records', 'Review management review minutes for discussions and decisions related to resource allocation (e.g., budget approval, new hires, equipment purchases). Check records like approved capital expenditure requests or hiring requisitions.', 18),
        (template_uuid, '6.2.1', 'Is there a documented procedure for determining competency, providing training, and ensuring awareness of personnel?', 'documentation', 'high', '6', 'Resource Management - This clause covers the people, infrastructure, and work environment needed to produce safe medical devices.', '6.2', 'Training and competency procedures', 'Review the procedure(s) for training and competency. This should define how training needs are assessed and how effectiveness is checked.', 19),
        (template_uuid, '6.2.2', 'Are personnel performing work affecting product quality competent based on education, training, skills, and experience?', 'verification', 'high', '6', 'Resource Management - This clause covers the people, infrastructure, and work environment needed to produce safe medical devices.', '6.2', 'Personnel training files and competency records', 'Select several employees and review their training files. Check that their files contain records of their qualifications (CVs, diplomas), job descriptions with competency requirements, and completed training records.', 20),
        (template_uuid, '6.3.1', 'Does the organization provide and maintain infrastructure needed to achieve conformity to product requirements?', 'verification', 'medium', '6', 'Resource Management - This clause covers the people, infrastructure, and work environment needed to produce safe medical devices.', '6.3', 'Infrastructure maintenance records and calibration certificates', 'Review maintenance schedules and records for key infrastructure (e.g., production equipment, HVAC systems, utilities). Check calibration certificates for measuring equipment.', 21),
        (template_uuid, '6.4.1', 'Does the organization determine and manage the work environment needed to achieve conformity to product requirements?', 'verification', 'medium', '6', 'Resource Management - This clause covers the people, infrastructure, and work environment needed to produce safe medical devices.', '6.4.1', 'Work environment monitoring records', 'Review environmental monitoring records (e.g., temperature, humidity, cleanliness). Check if there are specific requirements for the work environment in device specifications or regulatory requirements.', 22),
        (template_uuid, '6.4.2', 'Are there documented requirements for the health, cleanliness, and clothing of personnel?', 'documentation', 'high', '6', 'Resource Management - This clause covers the people, infrastructure, and work environment needed to produce safe medical devices.', '6.4.2', 'Personnel hygiene procedures and training records', 'Review procedures for personnel hygiene and clothing requirements. Check training records to ensure personnel are aware of these requirements. Observe personnel to verify compliance.', 23);
        
        -- Clause 7: Product Realization - 25 items (positions 24-48) 
        INSERT INTO gap_template_items (
            template_id, item_number, requirement_text, category, priority, clause_number, 
            clause_description, question_number, evidence_method, audit_guidance, sort_order
        ) VALUES 
        (template_uuid, '7.1.1', 'Does the organization plan and develop the processes needed for product realization?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.1', 'Product realization planning documents', 'Review the product realization planning documents. These should identify the specific processes, resources, and activities needed for each product or product family.', 24),
        (template_uuid, '7.2.1', 'Are customer requirements determined and documented?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.2.1', 'Customer requirement specifications and contracts', 'Review customer requirement specifications and contracts. Verify that all customer requirements, including regulatory requirements, are captured and documented.', 25),
        (template_uuid, '7.2.2', 'Is there a documented procedure for review of requirements related to the product?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.2.2', 'Contract review procedure and records', 'Review the contract review procedure and associated records. Verify that requirements are reviewed before acceptance and that any changes are communicated to relevant functions.', 26),
        (template_uuid, '7.2.3', 'Are there documented arrangements for communication with customers?', 'documentation', 'medium', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.2.3', 'Customer communication procedures and records', 'Review procedures for customer communication including feedback, complaints, and advisory notices. Check records of customer communications to verify the process is followed.', 27),
        (template_uuid, '7.3.1', 'Is there a documented procedure for design and development planning?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.1', 'Design control procedure and design plans', 'Review the design control procedure and design plans for current projects. Verify that design stages, activities, responsibilities, and authorities are defined.', 28),
        (template_uuid, '7.3.2', 'Are design and development inputs relating to product requirements determined, documented, and reviewed?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.2', 'Design input documents and review records', 'Review design input documents for completeness and clarity. Check that inputs include functional requirements, performance requirements, regulatory requirements, and risk management requirements.', 29),
        (template_uuid, '7.3.3', 'Are design and development outputs documented and expressed in terms suitable for verification against design inputs?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.3', 'Design output documents and specifications', 'Review design output documents including drawings, specifications, and software. Verify that outputs meet input requirements and contain acceptance criteria.', 30),
        (template_uuid, '7.3.4', 'Are systematic design and development reviews conducted at appropriate stages?', 'verification', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.4', 'Design review records and meeting minutes', 'Review design review records and meeting minutes. Verify that reviews are conducted at planned stages with appropriate participants and that results and actions are documented.', 31),
        (template_uuid, '7.3.5', 'Is design and development verification performed to ensure outputs meet input requirements?', 'verification', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.5', 'Design verification protocols and reports', 'Review design verification protocols and reports. Verify that verification methods are appropriate and that results demonstrate that design outputs meet design inputs.', 32),
        (template_uuid, '7.3.6', 'Is design and development validation performed to ensure the product meets user needs and intended use?', 'verification', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.6', 'Design validation protocols and clinical data', 'Review design validation protocols and reports including clinical evaluation data. Verify that validation demonstrates the device meets user needs under actual use conditions.', 33),
        (template_uuid, '7.3.7', 'Are design and development changes controlled and documented?', 'verification', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.7', 'Design change control records', 'Review design change control records. Verify that changes are documented, reviewed, approved, and that the impact on device safety and performance is evaluated.', 34),
        (template_uuid, '7.3.8', 'Are design and development files maintained for each device type or family?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.3.8', 'Design history files or design dossiers', 'Review design history files or design dossiers. Verify that all design and development records are maintained and readily retrievable.', 35),
        (template_uuid, '7.4.1', 'Does the organization have a documented procedure for purchasing process control?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.4.1', 'Purchasing procedure and supplier evaluations', 'Review the purchasing procedure and supplier evaluation records. Verify that the procedure defines criteria for supplier selection, evaluation, and ongoing monitoring.', 36),
        (template_uuid, '7.4.2', 'Are purchasing requirements clearly specified and communicated to suppliers?', 'documentation', 'medium', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.4.2', 'Purchase orders and specifications', 'Review purchase orders and specifications sent to suppliers. Verify that requirements are clearly specified including product specifications, quality requirements, and regulatory requirements.', 37),
        (template_uuid, '7.4.3', 'Are incoming products verified to ensure they meet specified requirements?', 'verification', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.4.3', 'Incoming inspection procedures and records', 'Review incoming inspection procedures and records. Verify that incoming products are inspected or otherwise verified before use and that nonconforming products are identified and controlled.', 38),
        (template_uuid, '7.5.1', 'Is production and service provision planned and carried out under controlled conditions?', 'verification', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.5.1', 'Production procedures and work instructions', 'Review production procedures and work instructions. Verify that they define the sequence of activities, required equipment, and acceptance criteria. Observe production activities for compliance.', 39),
        (template_uuid, '7.5.2', 'Are there documented procedures for validation of processes where output cannot be verified by monitoring or measurement?', 'documentation', 'high', '7', 'Product Realization - This clause covers the core processes for creating medical devices, from planning through delivery.', '7.5.2', 'Process validation procedures and reports', 'Review process validation procedures and reports for processes like sterilization, software, or welding. Verify that validation demonstrates the process consistently produces valid results.', 40);
        
        RAISE NOTICE 'Inserted Clause 6 and partial Clause 7 items (positions 18-40)';
    ELSE
        RAISE NOTICE 'ISO 13485 template not found - skipping data migration';
    END IF;
END $$;