-- Temporarily disable triggers and add documents directly
SET session_replication_role = replica;

-- Add documents directly without triggering template creation
INSERT INTO phase_assigned_documents (phase_id, name, document_type, document_scope, status, tech_applicability, description)
VALUES 
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Business Case / Project Charter', 'Standard', 'company_template', 'template', 'All device types', 'Project rationale, objectives, business justification.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Concept Brief', 'Standard', 'company_template', 'template', 'All device types', 'Defines initial concept, intended use, key features, target market, and regulatory strategy.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'User Needs Overview', 'Standard', 'company_template', 'template', 'All device types', 'Consolidated user requirements.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Early Competitive Landscape Summary', 'Standard', 'company_template', 'template', 'All device types', 'Market competitor analysis and positioning.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Draft Risk Management Plan', 'Quality', 'company_template', 'template', 'All device types', 'Preliminary document outlining approach to managing risks.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Feasibility Study Report (with risk inputs)', 'Standard', 'company_template', 'template', 'All device types', 'Documentation assessing device feasibility with an emphasis on initial risk assessment.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'High-Level Architecture / Concept Diagram', 'Technical', 'company_template', 'template', 'All device types', 'Visual diagrams outlining the device''s overall system architecture and components.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Initial Hazard Log / FMEA Entries', 'Quality', 'company_template', 'template', 'All device types', 'Early documentation of identified hazards and failure modes for risk management.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Intellectual Property (IP) Review', 'Standard', 'company_template', 'template', 'All device types', 'Evaluation of intellectual property considerations and protection strategies.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Preliminary Hazard Analysis (PHA)', 'Quality', 'company_template', 'template', 'All device types', 'Early-stage analysis identifying potential hazards and their impacts.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Preliminary Market Analysis', 'Standard', 'company_template', 'template', 'All device types', 'Early assessment of market potential, size, and dynamics.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Regulatory Strategy Outline', 'Regulatory', 'company_template', 'template', 'All device types', 'Document outlining the regulatory approval strategy and pathways.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Resource & Budget Feasibility Study', 'Standard', 'company_template', 'template', 'All device types', 'Analysis of resource requirements and budget considerations.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Quality Management Plan', 'Quality', 'company_template', 'template', 'All device types', 'Plan detailing overall quality management strategy and processes.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Internal Audit Reports', 'Quality', 'company_template', 'template', 'All device types', 'Reports documenting the findings of internal quality system audits.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Management Review Minutes', 'Quality', 'company_template', 'template', 'All device types', 'Records documenting management reviews of the quality system.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Periodic Audit / Review Schedule', 'Quality', 'company_template', 'template', 'All device types', 'Schedule documenting periodic internal and external audits.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Traceability Matrices (Req → Design → Verif → Valid → Risk)', 'Quality', 'company_template', 'template', 'All device types', 'Documentation demonstrating traceability across requirements, design, verification, validation, and risk management.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Design & Development Plan', 'Standard', 'company_template', 'template', 'All device types', 'Device development processes, resources, timelines.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Verification Test Reports (functional, EMC, biocomp., sterility, SW)', 'Quality', 'company_template', 'template', 'All device types', 'Documentation of results from various verification tests.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Biocompatibility Requirements', 'Clinical', 'company_template', 'template', 'Implantable devices', 'Biocompatibility testing and evaluation.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Calibration Certificates for Test Equipment', 'Quality', 'company_template', 'template', 'All device types', 'Calibration documentation for test equipment.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Design Review Records', 'Quality', 'company_template', 'template', 'All device types', 'Documentation of formal design reviews to ensure compliance and effectiveness.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'EMC Requirements (IEC 60601-1-2)', 'Regulatory', 'company_template', 'template', 'Electronic devices', 'Documentation ensuring compliance with electromagnetic compatibility standards.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Environmental & Sterilization Specs', 'Technical', 'company_template', 'template', 'Sterile devices', 'Specifications and procedures for environmental testing and sterilization.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Packaging Design Drawings', 'Technical', 'company_template', 'template', 'All device types', 'Technical drawings of packaging components.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Packaging Validation Reports', 'Quality', 'company_template', 'template', 'All device types', 'Reports documenting validation of packaging processes.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Pre-Clinical / Pre-Study Protocols', 'Clinical', 'company_template', 'template', 'All device types', 'Protocols for pre-clinical testing to assess device performance and safety.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Process Validation Protocols & Reports (sterility, shelf-life)', 'Quality', 'company_template', 'template', 'Sterile devices', 'Documentation of validation protocols and results for sterility and shelf-life.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Risk Control Implementation Records', 'Quality', 'company_template', 'template', 'All device types', 'Documentation detailing implementation of risk control measures.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Software Architecture & Code Documentation', 'Technical', 'company_template', 'template', 'Software devices', 'Documentation detailing the software architecture and source code.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Software Lifecycle Documentation (IEC 62304)', 'Technical', 'company_template', 'template', 'Software devices', 'Comprehensive documentation of the software development lifecycle.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Software Validation Reports (IQ/OQ/PQ)', 'Technical', 'company_template', 'template', 'Software devices', 'Reports documenting software validation activities and outcomes.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Sterilization & Shelf-Life Validation Summaries', 'Quality', 'company_template', 'template', 'Sterile devices', 'Reports summarizing validation of sterilization processes and product shelf-life.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Test Method Development Plan', 'Quality', 'company_template', 'template', 'All device types', 'Plan outlining methods for developing test procedures.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Test Method Validation Reports', 'Quality', 'company_template', 'template', 'All device types', 'Reports documenting validation of testing methods.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Updated Hazard Log / FMEA with Controls', 'Quality', 'company_template', 'template', 'All device types', 'Updated documentation of identified hazards, risks, and implemented controls.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Updated Traceability Matrix w/ Verification Links', 'Quality', 'company_template', 'template', 'All device types', 'Document linking design inputs and outputs directly to verification activities.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Verification Master Plan', 'Quality', 'company_template', 'template', 'All device types', 'Plan outlining the strategy and procedures for verification activities.'),
    ((SELECT id FROM phases WHERE name ILIKE '%Concept%' LIMIT 1), 'Verification Protocols & Acceptance Criteria', 'Quality', 'company_template', 'template', 'All device types', 'Detailed procedures and criteria for verifying design and performance specifications.');

-- Re-enable triggers
SET session_replication_role = DEFAULT;