-- Create standard_document_templates table with proper structure
CREATE TABLE standard_document_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  example TEXT,
  is_default BOOLEAN NOT NULL DEFAULT true,
  is_editable BOOLEAN NOT NULL DEFAULT true, 
  is_addable BOOLEAN NOT NULL DEFAULT true,
  document_type TEXT NOT NULL DEFAULT 'Standard',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE standard_document_templates ENABLE ROW LEVEL SECURITY;

-- Create policies for standard document templates
CREATE POLICY "Standard templates are viewable by everyone" 
ON standard_document_templates 
FOR SELECT 
USING (true);

CREATE POLICY "Only super admins can modify standard templates" 
ON standard_document_templates 
FOR ALL 
USING (is_admin_user())
WITH CHECK (is_admin_user());

-- Insert all default documents from standardDocData
INSERT INTO standard_document_templates (name, description, example, is_default, is_editable, is_addable, document_type, created_at, updated_at) VALUES
('Quality Management Plan', 'Plan detailing overall quality management strategy and processes.', 'Quality management strategy documentation.', true, true, true, 'Standard', now(), now()),
('Internal Audit Reports', 'Reports documenting the findings of internal quality system audits.', 'Internal audit documentation.', true, true, true, 'Standard', now(), now()),
('Management Review Minutes', 'Records documenting management reviews of the quality system.', 'Minutes from management review meetings.', true, true, true, 'Standard', now(), now()),
('Periodic Audit / Review Schedule', 'Schedule documenting periodic internal and external audits.', 'Annual audit schedule.', true, true, true, 'Standard', now(), now()),
('Traceability Matrices (Req → Design → Verif → Valid → Risk)', 'Documentation demonstrating traceability across requirements, design, verification, validation, and risk management.', 'Traceability matrices documentation.', true, true, true, 'Technical', now(), now()),
('Design & Development Plan', 'Device development processes, resources, timelines.', 'Detailed development timeline.', true, true, true, 'Standard', now(), now()),
('Verification Test Reports (functional, EMC, biocomp., sterility, SW)', 'Documentation of results from various verification tests.', 'Detailed verification test reports.', true, true, true, 'Technical', now(), now()),
('Biocompatibility Requirements', 'Biocompatibility testing and evaluation.', 'Biocompatibility test documentation.', true, true, true, 'Technical', now(), now()),
('Calibration Certificates for Test Equipment', 'Calibration documentation for test equipment.', 'Calibration certificates.', true, true, true, 'Technical', now(), now()),
('Design Review Records', 'Documentation of formal design reviews to ensure compliance and effectiveness.', 'Minutes from formal design reviews.', true, true, true, 'Standard', now(), now()),
('EMC Requirements (IEC 60601-1-2)', 'Documentation ensuring compliance with electromagnetic compatibility standards.', 'EMC test reports.', true, true, true, 'Technical', now(), now()),
('Environmental & Sterilization Specs', 'Specifications and procedures for environmental testing and sterilization.', 'Sterilization validation reports.', true, true, true, 'Technical', now(), now()),
('Packaging Design Drawings', 'Technical drawings of packaging components.', 'Packaging component CAD drawings.', true, true, true, 'Technical', now(), now()),
('Packaging Validation Reports', 'Reports documenting validation of packaging processes.', 'Packaging validation test reports.', true, true, true, 'Technical', now(), now()),
('Pre-Clinical / Pre-Study Protocols', 'Protocols for pre-clinical testing to assess device performance and safety.', 'Pre-clinical test protocols.', true, true, true, 'Clinical', now(), now()),
('Process Validation Protocols & Reports (sterility, shelf-life)', 'Documentation of validation protocols and results for sterility and shelf-life.', 'Validation testing protocols and reports.', true, true, true, 'Technical', now(), now()),
('Risk Control Implementation Records', 'Documentation detailing implementation of risk control measures.', 'Records of implemented risk controls.', true, true, true, 'Regulatory', now(), now()),
('Software Architecture & Code Documentation', 'Documentation detailing the software architecture and source code.', 'Software architecture diagrams, source code.', true, true, true, 'Technical', now(), now()),
('Software Lifecycle Documentation (IEC 62304)', 'Comprehensive documentation of the software development lifecycle.', 'Complete software lifecycle documents.', true, true, true, 'Technical', now(), now()),
('Software Validation Reports (IQ/OQ/PQ)', 'Reports documenting software validation activities and outcomes.', 'Software validation test reports.', true, true, true, 'Technical', now(), now()),
('Sterilization & Shelf-Life Validation Summaries', 'Reports summarizing validation of sterilization processes and product shelf-life.', 'Sterilization validation summary reports.', true, true, true, 'Technical', now(), now()),
('Test Method Development Plan', 'Plan outlining methods for developing test procedures.', 'Test method development document.', true, true, true, 'Technical', now(), now()),
('Test Method Validation Reports', 'Reports documenting validation of testing methods.', 'Test method validation reports.', true, true, true, 'Technical', now(), now()),
('Traceability Matrix (Inputs → Outputs → Controls)', 'Documentation showing the traceability of design inputs, outputs, and risk controls.', 'Detailed traceability matrix document.', true, true, true, 'Technical', now(), now()),
('Updated Hazard Log / FMEA with Controls', 'Updated documentation of identified hazards, risks, and implemented controls.', 'Updated hazard logs and FMEA documents.', true, true, true, 'Regulatory', now(), now()),
('Updated Traceability Matrix w/ Verification Links', 'Document linking design inputs and outputs directly to verification activities.', 'Comprehensive traceability document.', true, true, true, 'Technical', now(), now()),
('Verification Master Plan', 'Plan outlining the strategy and procedures for verification activities.', 'Verification master plan.', true, true, true, 'Technical', now(), now()),
('Verification Protocols & Acceptance Criteria', 'Detailed procedures and criteria for verifying design and performance specifications.', 'Verification testing protocols document.', true, true, true, 'Technical', now(), now()),
('CE Technical File & EU Declaration of Conformity', 'EU market entry technical and conformity documentation.', 'EU technical file and declaration.', true, true, true, 'Regulatory', now(), now()),
('Technical File / Design Dossier / Device Master Record', 'Comprehensive compilation of documentation required for regulatory submissions and production.', 'Complete technical file and documentation.', true, true, true, 'Regulatory', now(), now()),
('Business Case / Project Charter', 'Project rationale, objectives, business justification.', 'Charter with project objectives.', true, true, true, 'Standard', now(), now()),
('Concept Brief', 'Defines initial concept, intended use, key features, target market, and regulatory strategy.', 'Initial summary of diagnostic device.', true, true, true, 'Standard', now(), now()),
('Risk Management Report', 'Comprehensive summary of identified risks and controls.', 'Risk evaluation report.', true, true, true, 'Regulatory', now(), now()),
('User Needs Overview', 'Consolidated user requirements.', 'User feedback summary.', true, true, true, 'Standard', now(), now()),
('Detailed CAD Drawings & BOM', 'Technical drawings and Bill of Materials detailing device specifications.', 'CAD drawings and detailed parts list.', true, true, true, 'Technical', now(), now()),
('Device History File (DHF) Index', 'Index documenting all development records maintained for regulatory compliance.', 'Comprehensive index of design records.', true, true, true, 'Regulatory', now(), now()),
('Labeling & IFU Final', 'Final versions of labels and Instructions for Use for the device.', 'Final approved IFU and labeling.', true, true, true, 'Regulatory', now(), now()),
('Supplier Qualification Records', 'Documentation verifying qualifications and compliance of suppliers.', 'Supplier qualification reports.', true, true, true, 'Standard', now(), now()),
('Early Competitive Landscape Summary', 'Market competitor analysis and positioning.', 'Competitor overview report.', true, true, true, 'Standard', now(), now()),
('Draft Risk Management Plan', 'Preliminary document outlining approach to managing risks.', 'Initial risk management planning document.', true, true, true, 'Regulatory', now(), now()),
('Feasibility Study Report (with risk inputs)', 'Documentation assessing device feasibility with an emphasis on initial risk assessment.', 'Feasibility study documentation.', true, true, true, 'Standard', now(), now()),
('High-Level Architecture / Concept Diagram', 'Visual diagrams outlining the device''s overall system architecture and components.', 'System architecture diagrams.', true, true, true, 'Technical', now(), now()),
('Initial Hazard Log / FMEA Entries', 'Early documentation of identified hazards and failure modes for risk management.', 'Initial hazard identification logs.', true, true, true, 'Regulatory', now(), now()),
('Intellectual Property (IP) Review', 'Evaluation of intellectual property considerations and protection strategies.', 'IP assessment report.', true, true, true, 'Standard', now(), now()),
('Preliminary Hazard Analysis (PHA)', 'Early-stage analysis identifying potential hazards and their impacts.', 'Initial hazard identification document.', true, true, true, 'Regulatory', now(), now()),
('Preliminary Market Analysis', 'Early assessment of market potential, size, and dynamics.', 'Market research reports.', true, true, true, 'Standard', now(), now()),
('Regulatory Strategy Outline', 'Document outlining the regulatory approval strategy and pathways.', 'Regulatory strategy document.', true, true, true, 'Regulatory', now(), now()),
('Resource & Budget Feasibility Study', 'Assessment of required resources and budget for device development.', 'Resource planning document.', true, true, true, 'Standard', now(), now()),
('Stakeholder Requirements Specification', 'Document outlining requirements from various stakeholders including users, regulators, and business.', 'Stakeholder requirements document.', true, true, true, 'Standard', now(), now()),
('Clinical Evaluation Plan & Protocols', 'Plan and protocols for clinical evaluation of the device.', 'Clinical evaluation documentation.', true, true, true, 'Clinical', now(), now()),
('Clinical Investigation / Trial Protocols & CRFs', 'Protocols and case report forms for clinical trials.', 'Clinical trial documentation.', true, true, true, 'Clinical', now(), now()),
('Configuration Management Plan', 'Plan for managing configuration changes throughout development.', 'Configuration management procedures.', true, true, true, 'Technical', now(), now()),
('Design Input Requirements Spec (DIR)', 'Detailed specification of design input requirements.', 'Design requirements specification.', true, true, true, 'Technical', now(), now()),
('Human Factors Use-Specifications', 'Specifications for human factors engineering and usability.', 'Human factors documentation.', true, true, true, 'Clinical', now(), now()),
('Project Schedule / Gantt Chart', 'Detailed project timeline and scheduling documentation.', 'Project scheduling charts.', true, true, true, 'Standard', now(), now()),
('Regulatory & Standards Mapping Matrix', 'Matrix mapping applicable regulations and standards to device requirements.', 'Regulatory compliance matrix.', true, true, true, 'Regulatory', now(), now()),
('Regulatory Submission Roadmap', 'Timeline and strategy for regulatory submissions.', 'Regulatory submission planning.', true, true, true, 'Regulatory', now(), now()),
('Software Requirements Specification (SRS)', 'Detailed specification of software requirements and functionality.', 'Software requirements document.', true, true, true, 'Technical', now(), now()),
('Supplier Selection & Qualification Plan', 'Plan for selecting and qualifying suppliers and vendors.', 'Supplier qualification procedures.', true, true, true, 'Standard', now(), now()),
('Use Environment & Maintenance Profiles', 'Documentation of intended use environment and maintenance requirements.', 'Use environment specifications.', true, true, true, 'Technical', now(), now()),
('User Needs Specification (UNS)', 'Comprehensive specification of user needs and requirements.', 'User needs documentation.', true, true, true, 'Standard', now(), now()),
('Usability Engineering File (UEF)', 'Comprehensive file documenting usability engineering activities.', 'Usability engineering documentation.', true, true, true, 'Clinical', now(), now()),
('Validation Master Plan (Design, Clinical, Usability)', 'Master plan for all validation activities including design, clinical, and usability.', 'Validation planning document.', true, true, true, 'Technical', now(), now()),
('Design Validation Reports (simulated & actual use)', 'Reports documenting design validation under simulated and actual use conditions.', 'Design validation test reports.', true, true, true, 'Technical', now(), now()),
('Final Design Review Minutes', 'Minutes from final design review meetings.', 'Final design review documentation.', true, true, true, 'Standard', now(), now()),
('Design Transfer Plan', 'Plan for transferring design to manufacturing.', 'Design transfer procedures.', true, true, true, 'Standard', now(), now()),
('Design Transfer Review Records', 'Records from design transfer review activities.', 'Design transfer review documentation.', true, true, true, 'Standard', now(), now()),
('Manufacturing Process Documentation', 'Comprehensive documentation of manufacturing processes.', 'Manufacturing procedures.', true, true, true, 'Technical', now(), now()),
('Production Equipment Qualification', 'Documentation of production equipment qualification activities.', 'Equipment qualification reports.', true, true, true, 'Technical', now(), now()),
('Training Records for Production Staff', 'Records of training provided to production personnel.', 'Training documentation.', true, true, true, 'Standard', now(), now()),
('Change Control Review Minutes', 'Minutes from change control review meetings.', 'Change control documentation.', true, true, true, 'Standard', now(), now()),
('Change Implementation Records', 'Records documenting implementation of approved changes.', 'Change implementation documentation.', true, true, true, 'Standard', now(), now()),
('Change Request Forms', 'Forms used to request design or process changes.', 'Change request documentation.', true, true, true, 'Standard', now(), now()),
('Design Change Control Procedure', 'Procedure for managing design changes throughout lifecycle.', 'Change control procedures.', true, true, true, 'Standard', now(), now()),
('Impact Assessment Records', 'Records documenting impact assessment of proposed changes.', 'Impact assessment documentation.', true, true, true, 'Technical', now(), now()),
('Complete Hazard Log / FMEA', 'Comprehensive hazard log and failure mode analysis.', 'Complete hazard documentation.', true, true, true, 'Regulatory', now(), now()),
('Executive Sign-Off on Risk Acceptance', 'Executive approval and acceptance of residual risks.', 'Risk acceptance documentation.', true, true, true, 'Regulatory', now(), now()),
('Risk Management Plan (Final)', 'Final comprehensive risk management plan.', 'Final risk management documentation.', true, true, true, 'Regulatory', now(), now()),
('Risk/Benefit Analysis & Residual Risk Summary', 'Analysis of risks versus benefits and summary of residual risks.', 'Risk-benefit analysis documentation.', true, true, true, 'Regulatory', now(), now()),
('Configuration Management System', 'System for managing configuration and version control.', 'Configuration management procedures.', true, true, true, 'Technical', now(), now()),
('Document Control & Version Management', 'System for controlling documents and managing versions.', 'Document control procedures.', true, true, true, 'Standard', now(), now()),
('Training Records & Competency Documentation', 'Records of training and competency assessments.', 'Training and competency documentation.', true, true, true, 'Standard', now(), now()),
('Version Control Records', 'Records of version control activities and changes.', 'Version control documentation.', true, true, true, 'Technical', now(), now()),
('Product Launch Plan', 'Comprehensive plan for product launch activities.', 'Launch planning documentation.', true, true, true, 'Standard', now(), now()),
('Market Entry Strategy', 'Strategy for entering target markets.', 'Market entry planning.', true, true, true, 'Standard', now(), now()),
('Commercial Launch Readiness Checklist', 'Checklist to ensure readiness for commercial launch.', 'Launch readiness documentation.', true, true, true, 'Standard', now(), now()),
('Field Safety Corrective Action (FSCA) Records', 'Records of field safety corrective actions.', 'FSCA documentation.', true, true, true, 'Regulatory', now(), now()),
('Post-Market Clinical Follow-up (PMCF) Plan', 'Plan for post-market clinical follow-up activities.', 'PMCF planning documentation.', true, true, true, 'Clinical', now(), now()),
('Post-Market Surveillance Plan', 'Plan for ongoing post-market surveillance activities.', 'Post-market surveillance procedures.', true, true, true, 'Regulatory', now(), now()),
('Vigilance & Incident Reporting Procedures', 'Procedures for reporting incidents and adverse events.', 'Vigilance reporting procedures.', true, true, true, 'Regulatory', now(), now()),
('Contract Manufacturing Agreements', 'Agreements with contract manufacturers.', 'Manufacturing agreements.', true, true, true, 'Standard', now(), now()),
('Raw Material Specifications', 'Specifications for raw materials used in manufacturing.', 'Material specifications.', true, true, true, 'Technical', now(), now()),
('Supplier Audit Reports', 'Reports from supplier audits and assessments.', 'Supplier audit documentation.', true, true, true, 'Standard', now(), now()),
('Supplier / Contract Manufacturer Agreements', 'Agreements with suppliers and contract manufacturers.', 'Supplier agreements.', true, true, true, 'Standard', now(), now()),
('Supply Chain Risk Assessment', 'Assessment of risks within the supply chain.', 'Supply chain risk documentation.', true, true, true, 'Standard', now(), now()),
('Electrical Schematics & PCB Layouts', 'Electrical circuit diagrams and printed circuit board layouts.', 'Electrical design documentation.', true, true, true, 'Technical', now(), now()),
('Installation, Operation & Servicing Instructions Drafts', 'Draft instructions for installation, operation, and servicing.', 'Instruction documentation.', true, true, true, 'Technical', now(), now()),
('Labeling Drafts & UDI Assignments', 'Draft labeling and unique device identifier assignments.', 'Labeling documentation.', true, true, true, 'Regulatory', now(), now()),
('Manufacturing Process Flowcharts & Work Instructions', 'Flowcharts and work instructions for manufacturing processes.', 'Manufacturing documentation.', true, true, true, 'Technical', now(), now())
ON CONFLICT (name) DO NOTHING;