
-- Clear any existing items for MDR Annex I template
DELETE FROM gap_template_items WHERE template_id = '8b1ac5c4-28f0-4a5d-97ff-6bd093565e75';

-- Seed all 23 MDR Annex I GSPRs
INSERT INTO gap_template_items (template_id, item_number, clause_reference, requirement_text, chapter, category, priority, sort_order) VALUES
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 1', 'MDR_Annex_I_1', 'Devices shall achieve their intended performance without compromising safety during normal use conditions.', 'Chapter I: General Requirements', 'general', 'high', 1),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 2', 'MDR_Annex_I_2', 'Risk Management - Manufacturers shall establish, implement, document, and maintain a risk management system throughout the entire lifecycle.', 'Chapter I: General Requirements', 'general', 'high', 2),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 3', 'MDR_Annex_I_3', 'Chemical, Physical, and Biological Properties - Devices shall be designed and manufactured to ensure characteristics and performance.', 'Chapter I: General Requirements', 'general', 'medium', 3),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 4', 'MDR_Annex_I_4', 'Infection and Microbial Contamination - Devices shall be designed to minimize risks of infection to users and others.', 'Chapter I: General Requirements', 'general', 'medium', 4),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 5', 'MDR_Annex_I_5', 'Devices incorporating medicinal substances - Special requirements for devices that incorporate medicinal substances.', 'Chapter I: General Requirements', 'general', 'medium', 5),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 6', 'MDR_Annex_I_6', 'Devices utilizing tissues or cells of human or animal origin - Special requirements for devices using biological materials.', 'Chapter I: General Requirements', 'general', 'medium', 6),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 7', 'MDR_Annex_I_7', 'Software - Requirements for devices that incorporate software or that are software.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'high', 7),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 8', 'MDR_Annex_I_8', 'Active devices and devices connected to them - Requirements for powered medical devices.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'medium', 8),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 9', 'MDR_Annex_I_9', 'Devices emitting ionizing radiation - Special requirements for devices that emit ionizing radiation.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'medium', 9),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 10', 'MDR_Annex_I_10', 'Devices intended to administer medicinal products - Requirements for drug delivery devices.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'medium', 10),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 11', 'MDR_Annex_I_11', 'Devices incorporating a measuring function - Requirements for devices that measure biological parameters.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'medium', 11),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 12', 'MDR_Annex_I_12', 'Protection against radiation - Requirements for devices that emit non-ionizing radiation.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'medium', 12),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 13', 'MDR_Annex_I_13', 'Devices incorporating programmable electrical medical systems - Requirements for programmable medical devices.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'medium', 13),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 14', 'MDR_Annex_I_14', 'Active implantable devices - Special requirements for active implantable medical devices.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'medium', 14),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 15', 'MDR_Annex_I_15', 'Devices for contraception or prevention of sexually transmitted diseases - Special requirements for contraceptive devices.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'low', 15),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 16', 'MDR_Annex_I_16', 'Devices specifically intended for disinfecting, cleaning, rinsing - Requirements for cleaning and disinfection devices.', 'Chapter II: Requirements regarding design and manufacture', 'design_manufacture', 'low', 16),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 17', 'MDR_Annex_I_17', 'Information supplied by the manufacturer - Requirements for instructions for use and labeling.', 'Chapter III: Requirements regarding information supplied by the manufacturer', 'information', 'high', 17),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 18', 'MDR_Annex_I_18', 'Information on the label and in the instructions for use - Specific labeling requirements.', 'Chapter III: Requirements regarding information supplied by the manufacturer', 'information', 'high', 18),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 19', 'MDR_Annex_I_19', 'Unique Device Identification system - Requirements for UDI implementation.', 'Chapter III: Requirements regarding information supplied by the manufacturer', 'information', 'medium', 19),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 20', 'MDR_Annex_I_20', 'Information required on the device or on its packaging - Requirements for device identification.', 'Chapter III: Requirements regarding information supplied by the manufacturer', 'information', 'medium', 20),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 21', 'MDR_Annex_I_21', 'Information in the instructions for use - Detailed IFU requirements.', 'Chapter III: Requirements regarding information supplied by the manufacturer', 'information', 'high', 21),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 22', 'MDR_Annex_I_22', 'Minimum data set for the registration of devices - Requirements for device registration data.', 'Chapter III: Requirements regarding information supplied by the manufacturer', 'information', 'medium', 22),
('8b1ac5c4-28f0-4a5d-97ff-6bd093565e75', 'GSPR 23', 'MDR_Annex_I_23', 'Electronic systems for data collection - Requirements for data collection systems.', 'Chapter III: Requirements regarding information supplied by the manufacturer', 'information', 'low', 23);
