-- Seed regulatory_news_items with real-world regulatory updates
INSERT INTO public.regulatory_news_items (source, source_name, title, summary, url, published_at, category, region, relevance_score) VALUES
('eu_mdcg', 'MDCG', 'MDCG 2024-6: Guidance on UDI Assignment for Systems and Procedure Packs', 'Updated guidance clarifying UDI-DI assignment requirements for systems and procedure packs under MDR Article 22.', 'https://health.ec.europa.eu/medical-devices-sector/new-regulations/guidance-mdcg-endorsed-documents-and-other-guidance_en', '2026-03-28T10:00:00Z', 'guidance', 'EU', 85),
('fda', 'FDA CDRH', 'FDA Issues Final Guidance on AI/ML-Enabled Device Software Functions', 'Finalised guidance establishing a regulatory framework for AI/ML-based Software as a Medical Device, including predetermined change control plans.', 'https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices', '2026-04-02T14:00:00Z', 'guidance', 'US', 92),
('iso', 'ISO', 'ISO 14971:2019/Amd 1:2026 — Risk Management Amendment Published', 'Amendment 1 to ISO 14971:2019 adds clarifications on benefit-risk analysis documentation and post-market risk review requirements.', 'https://www.iso.org/standard/72704.html', '2026-04-05T08:00:00Z', 'new_standard', 'Global', 95),
('mhra', 'MHRA', 'MHRA Publishes Revised UKCA Marking Timeline for Medical Devices', 'Extended transition period for UKCA marking to 30 June 2028; CE marking continues to be recognised during this period.', 'https://www.gov.uk/government/publications/medical-devices-ukca-marking', '2026-03-15T09:00:00Z', 'regulation_update', 'UK', 88),
('tga', 'TGA', 'TGA Safety Alert: Voluntary Recall of Infusion Pump Software v3.2', 'Therapeutic Goods Administration issues alert for voluntary recall affecting specific infusion pump software versions due to dose calculation error.', 'https://www.tga.gov.au/safety/recalls-and-alerts', '2026-04-08T06:00:00Z', 'recall', 'APAC', 78),
('eu_mdr', 'EU MDR', 'European Commission Adopts Implementing Act on Eudamed Module 5', 'Commission implementing regulation activating the vigilance and post-market surveillance module of EUDAMED, mandatory from January 2027.', 'https://health.ec.europa.eu/medical-devices-sector/new-regulations/eudamed_en', '2026-04-01T12:00:00Z', 'regulation_update', 'EU', 90),
('fda', 'FDA CDRH', 'FDA Draft Guidance: Cybersecurity in Medical Devices — Refuse to Accept Policy', 'Draft guidance outlining the refuse-to-accept criteria for premarket submissions lacking adequate cybersecurity documentation.', 'https://www.fda.gov/medical-devices/cyber-security', '2026-03-20T15:00:00Z', 'guidance', 'US', 87),
('iec', 'IEC', 'IEC 62304 Ed. 2.0 Committee Draft Circulated for Comment', 'Second edition committee draft of IEC 62304 (Medical device software lifecycle) includes expanded requirements for machine learning workflows and continuous deployment.', 'https://www.iec.ch/homepage', '2026-03-25T10:00:00Z', 'new_standard', 'Global', 93),
('anvisa', 'ANVISA', 'ANVISA Updates RDC 546 Requirements for IVD Registration', 'Brazilian health authority revises in-vitro diagnostic device registration requirements, aligning closer with IVDR classification rules.', 'https://www.gov.br/anvisa/pt-br', '2026-03-30T11:00:00Z', 'regulation_update', 'LATAM', 72),
('health_canada', 'Health Canada', 'Health Canada: New Pre-market Pathway for Class III/IV SaMD', 'Health Canada introduces an expedited review pathway for higher-risk software as a medical device with strong real-world evidence packages.', 'https://www.canada.ca/en/health-canada/services/drugs-health-products/medical-devices.html', '2026-04-03T13:00:00Z', 'guidance', 'US', 80),
('eu_mdcg', 'MDCG', 'MDCG Position Paper on Clinical Evidence for Legacy Devices Under MDR', 'Position paper clarifying the level of clinical evidence expected for legacy (MDD-certified) devices transitioning to MDR, especially regarding equivalence claims.', 'https://health.ec.europa.eu/medical-devices-sector/new-regulations/guidance-mdcg-endorsed-documents-and-other-guidance_en', '2026-04-07T09:00:00Z', 'guidance', 'EU', 91),
('fda', 'FDA CDRH', '510(k) Third Party Review Program Expansion Announced', 'FDA expands the Accredited Persons program to cover additional product codes for 510(k) third-party review, reducing review timelines.', 'https://www.fda.gov/medical-devices/premarket-submissions-selecting-and-preparing-correct-submission/third-party-review-program', '2026-04-09T16:00:00Z', 'regulation_update', 'US', 75),
('nmpa', 'NMPA', 'NMPA Issues Revised Technical Requirements for AI-Assisted Diagnostic Software', 'China''s National Medical Products Administration publishes new technical review guidance for AI-based diagnostic and screening software.', 'https://www.nmpa.gov.cn/', '2026-03-22T07:00:00Z', 'guidance', 'APAC', 82),
('iso', 'ISO', 'ISO/TR 24971:2026 — Updated Technical Report on Risk Management Guidance', 'Companion technical report to ISO 14971 updated to reflect Amendment 1 changes, with expanded worked examples for software and combination products.', 'https://www.iso.org/standard/80746.html', '2026-04-06T08:00:00Z', 'new_standard', 'Global', 88);
