
-- Step 1: Delete all old records from both template tables
DELETE FROM default_document_templates;
DELETE FROM default_company_document_template;

-- Step 2: Insert 51 new Xyreg-native SOPs into default_document_templates
INSERT INTO default_document_templates (name, document_type, description) VALUES
-- QMS Foundation SOPs
('SOP-001 Quality Management System', 'SOP', 'Establishes the overarching QMS framework within Xyreg. Covers quality policy, objectives, and the interaction of all QMS processes managed through the platform.'),
('SOP-002 Document Control', 'SOP', 'Defines procedures for creating, reviewing, approving, and distributing controlled documents using the Xyreg Document Control module with electronic signatures and automated version control.'),
('SOP-003 Record Control', 'SOP', 'Governs identification, storage, protection, retrieval, retention, and disposition of quality records managed within Xyreg. Leverages the platform''s audit trail and record retention features.'),
('SOP-004 Management Review', 'SOP', 'Describes the process for conducting management reviews using Xyreg''s Management Review module, including agenda preparation, data collection from platform dashboards, and action tracking.'),
('SOP-005 Internal Audits', 'SOP', 'Defines the internal audit program managed through the Xyreg Audit Management module, including scheduling, planning, execution, findings tracking, and CAPA linkage.'),
('SOP-006 Training and Competence', 'SOP', 'Establishes training identification, delivery, and effectiveness evaluation procedures using the Xyreg Training Management module with automated training assignments and completion tracking.'),
('SOP-007 Risk Management', 'SOP', 'Defines the risk management process per ISO 14971 using the Xyreg Risk Management module, including hazard identification, risk estimation, evaluation, control, and residual risk assessment.'),
('SOP-008 Design and Development', 'SOP', 'Governs the design and development process using Xyreg Design Controls, including design planning, inputs, outputs, reviews, verification, validation, and transfer activities.'),
('SOP-009 Supplier Management', 'SOP', 'Defines supplier evaluation, qualification, monitoring, and re-evaluation using the Xyreg Supplier Management module with supplier scorecards and approved supplier list management.'),
('SOP-010 Production and Process Controls', 'SOP', 'Establishes production planning, process controls, and work environment requirements. References Xyreg''s production monitoring dashboards and process validation records.'),
('SOP-011 Control of Nonconforming Product', 'SOP', 'Defines identification, documentation, evaluation, segregation, and disposition of nonconforming product using the Xyreg NCR workflow with automated notifications and CAPA escalation.'),
('SOP-012 Corrective and Preventive Action (CAPA)', 'SOP', 'Governs the CAPA process using the Xyreg CAPA module, including problem identification, root cause analysis, action planning, implementation, verification of effectiveness, and closure.'),
('SOP-013 Complaint Handling', 'SOP', 'Defines complaint intake, investigation, trending, and regulatory reporting using the Xyreg Complaints module with automated vigilance assessment and CAPA linkage.'),
('SOP-014 Post-Market Surveillance (PMS)', 'SOP', 'Establishes systematic PMS activities using the Xyreg PMS module, including proactive and reactive data collection, trend analysis, PSUR/PMS report generation, and PMCF planning.'),
('SOP-015 Clinical Evaluation', 'SOP', 'Defines the clinical evaluation process including literature review, clinical data appraisal, and CER generation. Integrates with Xyreg''s Clinical module for study tracking and evidence management.'),
('SOP-016 Labeling and Packaging Control', 'SOP', 'Governs labeling design, review, approval, and control using Xyreg''s Labeling module with UDI management, label version control, and regulatory symbol libraries.'),
('SOP-017 Change Control', 'SOP', 'Defines the change control process using the Xyreg Change Control module, including change request initiation, impact assessment, approval workflows, implementation, and verification.'),
('SOP-018 Control of Monitoring and Measuring Equipment', 'SOP', 'Establishes calibration and maintenance procedures using Xyreg''s Calibration Management module with automated calibration scheduling, status tracking, and certificate management.'),
('SOP-019 Cybersecurity Management', 'SOP', 'Defines cybersecurity risk management for connected devices, including threat modeling, vulnerability assessment, patch management, and incident response aligned with FDA cybersecurity guidance.'),
('SOP-020 Statistical Techniques', 'SOP', 'Governs the selection and application of statistical methods for process capability, acceptance sampling, trend analysis, and data-driven decision making within the QMS.'),
('SOP-021 Purchasing Control', 'SOP', 'Defines purchasing processes including purchase order creation, supplier communication, and incoming goods verification. Integrates with Xyreg Supplier Management for approved supplier validation.'),
('SOP-022 Vigilance and Field Safety', 'SOP', 'Establishes vigilance reporting procedures using the Xyreg Vigilance module, including reportability assessment, authority notification timelines, field safety corrective actions (FSCA), and trend reporting.'),
('SOP-023 Device Service and Maintenance', 'SOP', 'Defines field service, installation, and maintenance procedures including service report management, spare parts control, and feedback collection for post-market data.'),
('SOP-024 Environmental Monitoring', 'SOP', 'Establishes environmental monitoring and control procedures for cleanrooms and controlled production areas, including particulate monitoring, temperature, humidity, and microbial controls.'),
('SOP-025 Sterilization Process Control', 'SOP', 'Defines sterilization process development, validation, and routine control procedures including bioburden testing, sterility assurance level (SAL) determination, and parametric release criteria.'),
('SOP-026 Biocompatibility Evaluation', 'SOP', 'Governs biological evaluation of medical devices per ISO 10993, including material characterization, toxicological risk assessment, and biocompatibility testing strategy.'),
('SOP-027 Usability Engineering', 'SOP', 'Defines the usability engineering process per IEC 62366, including use specification, hazard-related use scenarios, user interface evaluation, and summative usability testing.'),
('SOP-028 Software Development Lifecycle (SDLC)', 'SOP', 'Establishes software development processes per IEC 62304, including software classification, architecture design, unit testing, integration testing, and software maintenance.'),
('SOP-029 Electrical Safety and EMC', 'SOP', 'Defines procedures for ensuring electrical safety per IEC 60601 and electromagnetic compatibility testing, including essential performance verification and risk-based test planning.'),
('SOP-030 Process Validation', 'SOP', 'Governs process validation methodology including IQ/OQ/PQ protocols, process capability assessment, and ongoing process verification for special processes.'),
('SOP-031 Verification and Validation', 'SOP', 'Defines V&V planning, protocol development, execution, and reporting procedures. Integrates with Xyreg Design Controls for traceability between requirements and test evidence.'),
('SOP-032 Product Identification and Traceability', 'SOP', 'Establishes product identification, lot/serial number assignment, and traceability procedures including UDI-DI/UDI-PI management through the Xyreg UDI module.'),
('SOP-033 Preservation of Product', 'SOP', 'Defines handling, storage, packaging, and delivery requirements to maintain product conformity throughout the supply chain, including shelf-life determination and storage condition monitoring.'),
('SOP-034 Regulatory Submission Management', 'SOP', 'Governs regulatory submission planning, preparation, and lifecycle management for global markets including 510(k), CE marking, and international registrations using Xyreg Regulatory Intelligence.'),
('SOP-035 UDI Management', 'SOP', 'Defines UDI assignment, database submission (GUDID/EUDAMED), and label integration procedures using the Xyreg UDI module with automated Basic UDI-DI and UDI-DI management.'),
('SOP-036 Technical Documentation Management', 'SOP', 'Establishes procedures for creating and maintaining technical documentation (Design Dossier/STED) using Xyreg''s document management with structured content templates and cross-referencing.'),
('SOP-037 Post-Market Clinical Follow-up (PMCF)', 'SOP', 'Defines PMCF planning, execution, and reporting procedures using the Xyreg Clinical module, including PMCF study design, data collection, and integration with PMS activities.'),
('SOP-038 Periodic Safety Update Report (PSUR)', 'SOP', 'Governs PSUR/PMS report preparation, review, and submission procedures. Leverages Xyreg''s automated data aggregation from complaints, vigilance, and clinical modules.'),
('SOP-039 Bill of Materials (BOM) Management', 'SOP', 'Defines BOM creation, revision control, and approval workflows using the Xyreg BOM module with component traceability, supplier linkage, and cost tracking.'),
('SOP-040 Shelf Life and Stability Testing', 'SOP', 'Establishes accelerated and real-time aging study design, execution, and data analysis procedures for determining product shelf life and packaging integrity.'),
('SOP-041 Cleaning and Disinfection', 'SOP', 'Defines cleaning validation, reprocessing instructions development, and disinfection procedures for reusable medical devices per manufacturer guidelines.'),
('SOP-042 Customer Communication and Feedback', 'SOP', 'Governs customer feedback collection, satisfaction measurement, and communication procedures. Integrates with Xyreg Complaints and PMS modules for systematic feedback analysis.'),
('SOP-043 Outsourced Process Control', 'SOP', 'Defines requirements for managing outsourced processes including quality agreements, performance monitoring, and verification of outsourced activities.'),
('SOP-044 Product Recall and Advisory Notice', 'SOP', 'Establishes procedures for initiating, executing, and closing product recalls and advisory notices. Integrates with Xyreg Vigilance module for regulatory authority coordination.'),
('SOP-045 EUDAMED Registration', 'SOP', 'Defines procedures for actor registration, UDI/device registration, certificate uploads, and vigilance reporting through the EUDAMED database using Xyreg regulatory tools.'),
('SOP-046 Data Integrity', 'SOP', 'Establishes ALCOA+ principles for ensuring data integrity across all electronic and paper-based quality records, including access controls, audit trails, and backup procedures.'),
('SOP-047 Combination Product Management', 'SOP', 'Defines procedures for managing combination products (drug-device, biologic-device) including primary mode of action determination, regulatory pathway selection, and cross-functional coordination.'),
('SOP-048 In Vitro Diagnostic (IVD) Specific Procedures', 'SOP', 'Governs IVD-specific requirements including performance evaluation, reference measurement procedures, and IVDR classification under the Xyreg regulatory framework.'),
('SOP-049 Human Factors Engineering', 'SOP', 'Defines human factors engineering processes including task analysis, use error analysis, and formative/summative evaluations per FDA HFE guidance and IEC 62366.'),
('SOP-050 Continual Improvement', 'SOP', 'Establishes systematic continual improvement procedures using data from Xyreg dashboards including CAPA trends, audit findings, management review outputs, and process metrics.'),
('SOP-051 Quality Agreement Management', 'SOP', 'Defines requirements for establishing, reviewing, and maintaining quality agreements with suppliers, contract manufacturers, and service providers using Xyreg Supplier Management.');

-- Step 3: Insert 19 updated Forms into default_document_templates
INSERT INTO default_document_templates (name, document_type, description) VALUES
('FORM-001-A Document Change Order (DCO)', 'Form', 'Managed digitally within the Xyreg Document Control module. Initiate a DCO from Settings > Document Control or from any document''s action menu to trigger the electronic review and approval workflow.'),
('FORM-003-A Management Review Meeting Minutes', 'Form', 'Template for recording management review meeting outcomes including attendees, agenda items discussed, decisions made, and action items assigned. Use with SOP-004 Management Review.'),
('FORM-004-B Internal Audit Plan', 'Form', 'Managed digitally within the Xyreg Audit Management module. Create audit plans from Quality Operations > Audits with automated scheduling, scope definition, and auditor assignment.'),
('FORM-004-C Internal Audit Report', 'Form', 'Managed digitally within the Xyreg Audit Management module. Complete audit reports from the audit record with findings classification, evidence attachment, and CAPA linkage.'),
('FORM-005-B Training Roster', 'Form', 'Managed digitally within the Xyreg Training Management module. Training records are automatically created and tracked from Settings > Training with completion status and effectiveness evaluation.'),
('FORM-006-B Design Review Meeting Minutes', 'Form', 'Template for recording design review outcomes including review participants, design stage evaluated, action items, and design decision (proceed/hold/cancel). Use with SOP-008 Design and Development.'),
('FORM-009-A Supplier Quality Questionnaire', 'Form', 'Managed digitally within the Xyreg Supplier Management module. Send supplier questionnaires from Quality Operations > Suppliers with automated scoring and qualification tracking.'),
('FORM-009-B Supplier Evaluation Report', 'Form', 'Managed digitally within the Xyreg Supplier Management module. Generate supplier evaluation reports from the supplier record with performance metrics, audit findings, and approval recommendations.'),
('FORM-011-A Nonconformance Report (NCR)', 'Form', 'Managed digitally within the Xyreg NCR workflow. Create NCRs from Quality Operations > NCRs with automated notifications, disposition tracking, and CAPA escalation.'),
('FORM-012-A CAPA Request Form', 'Form', 'Managed digitally within the Xyreg CAPA module. Initiate CAPAs from Quality Operations > CAPA with source linkage, risk assessment, and automated workflow routing.'),
('FORM-012-C CAPA Record', 'Form', 'Managed digitally within the Xyreg CAPA module. The full CAPA record including investigation, root cause analysis, action plans, and verification of effectiveness is managed within the CAPA workflow.'),
('FORM-013-B Complaint File', 'Form', 'Managed digitally within the Xyreg Complaints module. Create and manage complaint records from Quality Operations > Complaints with automated vigilance assessment and trend analysis.'),
('FORM-013-C Health Hazard Evaluation (HHE)', 'Form', 'Managed digitally within the Xyreg Complaints module. The HHE is triggered automatically during complaint investigation when potential health hazards are identified, with risk-based reportability assessment.'),
('FORM-016-A Labeling Approval Form', 'Form', 'Template for documenting labeling review and approval decisions including regulatory symbol verification, UDI accuracy check, translation review, and final artwork sign-off. Use with SOP-016.'),
('FORM-017-A Change Control Request (CCR)', 'Form', 'Managed digitally within the Xyreg Change Control module. Initiate change requests from the Change Control section with impact assessment, approval workflows, and implementation tracking.'),
('FORM-018-B Calibration Record', 'Form', 'Template for documenting calibration activities including instrument identification, calibration standard used, measurements taken, pass/fail determination, and next calibration due date. Use with SOP-018.'),
('FORM-021-A Incoming Inspection Record', 'Form', 'Template for documenting incoming goods inspection including supplier, PO reference, lot/batch number, inspection criteria, measurements, and accept/reject disposition. Use with SOP-021.'),
('FORM-022-A Reportability Assessment Form', 'Form', 'Managed digitally within the Xyreg Vigilance module. Reportability assessments are triggered from complaint records with guided regulatory criteria evaluation and authority notification tracking.'),
('FORM-023-A Service Report', 'Form', 'Template for documenting field service activities including device identification, issue description, actions taken, parts replaced, and post-service verification. Use with SOP-023.');

-- Step 4: Insert 8 updated Lists into default_document_templates
INSERT INTO default_document_templates (name, document_type, description) VALUES
('LIST-001-B Master Document List (MDL)', 'List', 'Auto-generated within the Xyreg Document Control module. Access the live MDL from Settings > Document Control showing all controlled documents with current revision status, approval dates, and review schedules.'),
('LIST-002-A Record Retention Schedule', 'List', 'Template for defining record types, retention periods, storage locations, and disposition methods. Maintains compliance with regulatory retention requirements across all markets. Use with SOP-003.'),
('LIST-004-A Internal Audit Schedule', 'List', 'Managed digitally within the Xyreg Audit Management module. The audit schedule is maintained from Quality Operations > Audits with automated frequency tracking and coverage analysis.'),
('LIST-005-A Training Matrix', 'List', 'Managed digitally within the Xyreg Training Management module. The training matrix showing role-based training requirements and completion status is accessible from Settings > Training.'),
('LIST-009-C Approved Supplier List (ASL)', 'List', 'Managed digitally within the Xyreg Supplier Management module. The ASL is maintained from Quality Operations > Suppliers showing qualification status, approved materials/services, and re-evaluation dates.'),
('LIST-012-B CAPA Log', 'List', 'Managed digitally within the Xyreg CAPA module. The CAPA log with status tracking, trending, and metrics is accessible from Quality Operations > CAPA dashboard.'),
('LIST-013-A Complaint Log', 'List', 'Managed digitally within the Xyreg Complaints module. The complaint log with trending, product analysis, and regulatory reporting status is accessible from Quality Operations > Complaints dashboard.'),
('LIST-018-A Master Equipment List', 'List', 'Template for maintaining an inventory of production and quality equipment including instrument ID, calibration status, location, and responsible person. Use with SOP-018.');

-- Step 5: Insert 20 priority SOPs into default_company_document_template
INSERT INTO default_company_document_template (name, document_type, description) VALUES
('SOP-001 Quality Management System', 'SOP', 'Establishes the overarching QMS framework within Xyreg. Covers quality policy, objectives, and the interaction of all QMS processes managed through the platform.'),
('SOP-002 Document Control', 'SOP', 'Defines procedures for creating, reviewing, approving, and distributing controlled documents using the Xyreg Document Control module with electronic signatures and automated version control.'),
('SOP-003 Record Control', 'SOP', 'Governs identification, storage, protection, retrieval, retention, and disposition of quality records managed within Xyreg.'),
('SOP-004 Management Review', 'SOP', 'Describes the process for conducting management reviews using Xyreg''s Management Review module.'),
('SOP-005 Internal Audits', 'SOP', 'Defines the internal audit program managed through the Xyreg Audit Management module.'),
('SOP-006 Training and Competence', 'SOP', 'Establishes training identification, delivery, and effectiveness evaluation procedures using the Xyreg Training Management module.'),
('SOP-007 Risk Management', 'SOP', 'Defines the risk management process per ISO 14971 using the Xyreg Risk Management module.'),
('SOP-008 Design and Development', 'SOP', 'Governs the design and development process using Xyreg Design Controls.'),
('SOP-009 Supplier Management', 'SOP', 'Defines supplier evaluation, qualification, monitoring, and re-evaluation using the Xyreg Supplier Management module.'),
('SOP-010 Production and Process Controls', 'SOP', 'Establishes production planning, process controls, and work environment requirements.'),
('SOP-011 Control of Nonconforming Product', 'SOP', 'Defines identification, documentation, evaluation, segregation, and disposition of nonconforming product using the Xyreg NCR workflow.'),
('SOP-012 Corrective and Preventive Action (CAPA)', 'SOP', 'Governs the CAPA process using the Xyreg CAPA module.'),
('SOP-013 Complaint Handling', 'SOP', 'Defines complaint intake, investigation, trending, and regulatory reporting using the Xyreg Complaints module.'),
('SOP-014 Post-Market Surveillance (PMS)', 'SOP', 'Establishes systematic PMS activities using the Xyreg PMS module.'),
('SOP-015 Clinical Evaluation', 'SOP', 'Defines the clinical evaluation process including literature review, clinical data appraisal, and CER generation.'),
('SOP-016 Labeling and Packaging Control', 'SOP', 'Governs labeling design, review, approval, and control using Xyreg''s Labeling module with UDI management.'),
('SOP-017 Change Control', 'SOP', 'Defines the change control process using the Xyreg Change Control module.'),
('SOP-018 Control of Monitoring and Measuring Equipment', 'SOP', 'Establishes calibration and maintenance procedures using Xyreg''s Calibration Management module.'),
('SOP-022 Vigilance and Field Safety', 'SOP', 'Establishes vigilance reporting procedures using the Xyreg Vigilance module.'),
('SOP-034 Regulatory Submission Management', 'SOP', 'Governs regulatory submission planning, preparation, and lifecycle management for global markets using Xyreg Regulatory Intelligence.');
