// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzzkbmmgxxrfhhxggrcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6emtibW1neHhyZmhoeGdncmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTY1OTksImV4cCI6MjA2MDk3MjU5OX0.IILyYxMvAEyt5DrRWvF7NR0omsg2DKbhh5b-C4N73ME";

// Capture password recovery flow BEFORE createClient() processes and clears the URL hash.
// Supabase client auto-detects #type=recovery in the hash on init, fires PASSWORD_RECOVERY
// event, then clears the hash — all before React mounts. So we flag it here synchronously.
if (typeof window !== 'undefined' && window.location.hash.includes('type=recovery')) {
  sessionStorage.setItem('pending_password_recovery', 'true');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);