import { Question, ClassificationResult } from '@/types/classification';

// Australia TGA Medical Device Classification Rules
// Based on the Therapeutic Goods (Medical Devices) Regulations 2002
// Aligned with GHTF/IMDRF principles and similar to EU MDR

export const australiaClassificationQuestions: Record<string, Question> = {
  initial: {
    id: 'initial',
    text: 'Is this product a medical device?',
    description: 'A medical device means an instrument, apparatus, appliance, software, implant, reagent, material or other article intended for use in human beings for medical purposes.',
    options: [
      {
        id: 'yes',
        text: 'Yes, this is a medical device',
        nextQuestionId: 'principal_mode_of_action'
      },
      {
        id: 'no',
        text: 'No, this is not a medical device',
        result: {
          class: 'Not a medical device',
          rule: 'TGA Regulations 2002',
          description: 'Product does not meet the definition of a medical device under Australian regulations.'
        }
      }
    ]
  },

  principal_mode_of_action: {
    id: 'principal_mode_of_action',
    text: 'Does the product achieve its principal intended action by pharmacological, immunological, or metabolic means?',
    description: 'Medical devices typically achieve their principal action by other means (e.g., physical, mechanical). They can be assisted by pharmacological, immunological, or metabolic means, but these should not be the principal mode of action.',
    options: [
      {
        id: 'yes_pharma',
        text: 'Yes, its principal action is through these means',
        result: {
          class: 'Consultation required',
          rule: 'TGA Regulations 2002',
          description: 'Product may not be a medical device if its principal intended action is pharmacological, immunological, or metabolic. Consultation with TGA recommended.'
        }
      },
      {
        id: 'no_other',
        text: 'No, its principal action is by other means',
        nextQuestionId: 'invasiveness'
      }
    ]
  },

  invasiveness: {
    id: 'invasiveness',
    text: 'Is the device invasive?',
    description: 'An invasive device partially or wholly penetrates the body, either through a body orifice or through the surface of the body.',
    options: [
      {
        id: 'non_invasive',
        text: 'Non-invasive',
        nextQuestionId: 'active_device'
      },
      {
        id: 'invasive',
        text: 'Invasive',
        nextQuestionId: 'surgically_invasive'
      }
    ]
  },

  surgically_invasive: {
    id: 'surgically_invasive',
    text: 'Is the device surgically invasive?',
    description: 'A surgically invasive device penetrates the body through the surface with the aid or in the context of a surgical operation.',
    options: [
      {
        id: 'yes',
        text: 'Yes, surgically invasive',
        nextQuestionId: 'implantable'
      },
      {
        id: 'no',
        text: 'No, not surgically invasive',
        nextQuestionId: 'body_orifice'
      }
    ]
  },

  implantable: {
    id: 'implantable',
    text: 'Is the device implantable?',
    description: 'An implantable device is intended to be totally introduced into the body or to replace an epithelial surface and remain after the procedure.',
    options: [
      {
        id: 'yes',
        text: 'Yes, implantable',
        nextQuestionId: 'active_implantable'
      },
      {
        id: 'no',
        text: 'No, not implantable',
        nextQuestionId: 'duration_surgical'
      }
    ]
  },

  active_implantable: {
    id: 'active_implantable',
    text: 'Is this an active implantable device?',
    description: 'An active implantable device relies on a source of energy other than that directly generated by the human body or gravity.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active implantable',
        result: {
          class: 'Class III',
          rule: 'TGA Rule 7',
          description: 'All active implantable medical devices are classified as Class III.'
        }
      },
      {
        id: 'no',
        text: 'No, not active implantable',
        nextQuestionId: 'cardiovascular_cns'
      }
    ]
  },

  cardiovascular_cns: {
    id: 'cardiovascular_cns',
    text: 'Does the device come into contact with the cardiovascular system or central nervous system?',
    description: 'Consider if the device is intended to be used in direct contact with the heart, central circulatory system, brain, or spinal cord.',
    options: [
      {
        id: 'yes',
        text: 'Yes, contacts cardiovascular system or CNS',
        result: {
          class: 'Class III',
          rule: 'TGA Rule 6',
          description: 'Implantable devices in contact with the cardiovascular system or CNS are Class III.'
        }
      },
      {
        id: 'no',
        text: 'No, does not contact these systems',
        nextQuestionId: 'implant_duration'
      }
    ]
  },

  implant_duration: {
    id: 'implant_duration',
    text: 'What is the intended duration of implantation?',
    options: [
      {
        id: 'long_term',
        text: 'Long term (> 30 days)',
        result: {
          class: 'Class IIb',
          rule: 'TGA Rule 8',
          description: 'Long-term implantable devices are Class IIb.'
        }
      },
      {
        id: 'short_term',
        text: 'Short term (≤ 30 days)',
        result: {
          class: 'Class IIa',
          rule: 'TGA Rule 5',
          description: 'Short-term implantable devices are Class IIa.'
        }
      }
    ]
  },

  duration_surgical: {
    id: 'duration_surgical',
    text: 'What is the duration of use for this surgically invasive device?',
    options: [
      {
        id: 'transient',
        text: 'Transient (≤ 60 minutes)',
        result: {
          class: 'Class IIa',
          rule: 'TGA Rule 5',
          description: 'Transient surgically invasive devices are Class IIa.'
        }
      },
      {
        id: 'short_term',
        text: 'Short term (> 60 minutes to 30 days)',
        nextQuestionId: 'reusable_surgical'
      },
      {
        id: 'long_term',
        text: 'Long term (> 30 days)',
        result: {
          class: 'Class IIb',
          rule: 'TGA Rule 8',
          description: 'Long-term surgically invasive devices are Class IIb.'
        }
      }
    ]
  },

  reusable_surgical: {
    id: 'reusable_surgical',
    text: 'Is this a reusable surgical instrument?',
    description: 'Reusable surgical instruments are intended for surgical purposes to cut, drill, saw, or perform similar procedures, without connection to an active device.',
    options: [
      {
        id: 'yes',
        text: 'Yes, reusable surgical instrument',
        result: {
          class: 'Class I',
          rule: 'TGA Rule 4',
          description: 'Reusable surgical instruments are Class I with special requirements.'
        }
      },
      {
        id: 'no',
        text: 'No, not a reusable surgical instrument',
        result: {
          class: 'Class IIa',
          rule: 'TGA Rule 5',
          description: 'Short-term surgically invasive devices are Class IIa.'
        }
      }
    ]
  },

  body_orifice: {
    id: 'body_orifice',
    text: 'Does the device enter the body through a body orifice?',
    description: 'Consider natural body openings such as mouth, nose, ears, eyes, or other natural openings.',
    options: [
      {
        id: 'yes',
        text: 'Yes, enters through body orifice',
        nextQuestionId: 'orifice_depth'
      },
      {
        id: 'no',
        text: 'No, does not enter body',
        result: {
          class: 'Class I',
          rule: 'TGA Rule 1',
          description: 'Non-invasive devices are generally Class I.'
        }
      }
    ]
  },

  orifice_depth: {
    id: 'orifice_depth',
    text: 'Does the device penetrate beyond the pharynx, ear canal, or nasal cavity?',
    options: [
      {
        id: 'yes',
        text: 'Yes, penetrates beyond these areas',
        result: {
          class: 'Class IIa',
          rule: 'TGA Rule 5',
          description: 'Invasive devices through body orifices that penetrate beyond pharynx, ear canal, or nasal cavity are Class IIa.'
        }
      },
      {
        id: 'no',
        text: 'No, remains in these areas',
        result: {
          class: 'Class I',
          rule: 'TGA Rule 1',
          description: 'Invasive devices through body orifices that remain in pharynx, ear canal, or nasal cavity are Class I.'
        }
      }
    ]
  },

  active_device: {
    id: 'active_device',
    text: 'Is this an active device?',
    description: 'An active device relies on a source of energy other than that directly generated by the human body or gravity.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active device',
        nextQuestionId: 'active_therapeutic'
      },
      {
        id: 'no',
        text: 'No, non-active device',
        result: {
          class: 'Class I',
          rule: 'TGA Rule 1',
          description: 'Non-active, non-invasive devices are Class I.'
        }
      }
    ]
  },

  active_therapeutic: {
    id: 'active_therapeutic',
    text: 'Is this an active therapeutic device?',
    description: 'An active therapeutic device is intended to administer or exchange energy to or with the patient.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active therapeutic device',
        result: {
          class: 'Class IIa',
          rule: 'TGA Rule 9',
          description: 'Active therapeutic devices are generally Class IIa.'
        }
      },
      {
        id: 'no',
        text: 'No, active diagnostic device',
        result: {
          class: 'Class IIa',
          rule: 'TGA Rule 10',
          description: 'Active diagnostic devices are generally Class IIa.'
        }
      }
    ]
  }
};
