import { Question, ClassificationResult } from '@/types/classification';

// Canada Health Canada Medical Device Classification Rules (CMDCAS)
// Based on the Canadian Medical Devices Regulations (SOR/98-282)

export const canadaClassificationQuestions: Record<string, Question> = {
  initial: {
    id: 'initial',
    text: 'Is this product a medical device?',
    description: 'A medical device under Canadian regulations means an instrument, apparatus, implement, machine, contrivance, implant, in vitro reagent, or other similar or related article intended for use in the diagnosis, treatment, mitigation or prevention of a disease, disorder or abnormal physical state.',
    options: [
      {
        id: 'yes',
        text: 'Yes, this is a medical device',
        nextQuestionId: 'invasiveness'
      },
      {
        id: 'no',
        text: 'No, this is not a medical device',
        result: {
          class: 'Not a medical device',
          rule: 'Canadian Medical Devices Regulations',
          description: 'Product does not meet the definition of a medical device under Canadian regulations.'
        }
      }
    ]
  },

  invasiveness: {
    id: 'invasiveness',
    text: 'Is the device invasive?',
    description: 'An invasive device partially or wholly penetrates inside the body, either through a body orifice or through the surface of the body.',
    options: [
      {
        id: 'non_invasive',
        text: 'Non-invasive',
        nextQuestionId: 'duration_contact'
      },
      {
        id: 'invasive',
        text: 'Invasive',
        nextQuestionId: 'surgically_invasive'
      }
    ]
  },

  surgically_invasive: {
    id: 'surgically_invasive',
    text: 'Is the device surgically invasive?',
    description: 'A surgically invasive device penetrates inside the body through the surface of the body with the aid or in the context of a surgical operation.',
    options: [
      {
        id: 'yes',
        text: 'Yes, surgically invasive',
        nextQuestionId: 'implantable'
      },
      {
        id: 'no',
        text: 'No, not surgically invasive',
        nextQuestionId: 'body_orifice'
      }
    ]
  },

  implantable: {
    id: 'implantable',
    text: 'Is the device implantable?',
    description: 'An implantable device is intended to be totally introduced into the human body or to replace an epithelial surface through clinical intervention and remain in place after the procedure.',
    options: [
      {
        id: 'yes',
        text: 'Yes, implantable',
        nextQuestionId: 'active_implantable'
      },
      {
        id: 'no',
        text: 'No, not implantable',
        nextQuestionId: 'contact_heart_cns'
      }
    ]
  },

  active_implantable: {
    id: 'active_implantable',
    text: 'Is this an active implantable device?',
    description: 'An active implantable device relies on a source of energy other than that directly generated by the human body or gravity.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active implantable',
        result: {
          class: 'Class IV',
          rule: 'Canada Rule 12',
          description: 'All active implantable medical devices are classified as Class IV.'
        }
      },
      {
        id: 'no',
        text: 'No, not active',
        nextQuestionId: 'implant_duration'
      }
    ]
  },

  implant_duration: {
    id: 'implant_duration',
    text: 'What is the intended duration of implantation?',
    description: 'Consider how long the device is intended to remain implanted in the body.',
    options: [
      {
        id: 'short_term',
        text: 'Short term (≤ 30 days)',
        result: {
          class: 'Class III',
          rule: 'Canada Rule 7',
          description: 'Short-term surgically invasive implantable devices are Class III.'
        }
      },
      {
        id: 'long_term',
        text: 'Long term (> 30 days)',
        nextQuestionId: 'contact_heart_cns'
      }
    ]
  },

  contact_heart_cns: {
    id: 'contact_heart_cns',
    text: 'Does the device come into contact with the heart, central circulatory system, or central nervous system?',
    description: 'Consider if the device is intended to be used in direct contact with the heart, central circulatory system, or central nervous system.',
    options: [
      {
        id: 'yes',
        text: 'Yes, contacts heart/CNS/central circulation',
        result: {
          class: 'Class IV',
          rule: 'Canada Rule 8',
          description: 'Long-term implantable devices in contact with the heart, central circulatory system, or central nervous system are Class IV.'
        }
      },
      {
        id: 'no',
        text: 'No, does not contact these areas',
        result: {
          class: 'Class III',
          rule: 'Canada Rule 7',
          description: 'Long-term implantable devices not in contact with the heart, CNS, or central circulation are Class III.'
        }
      }
    ]
  },

  body_orifice: {
    id: 'body_orifice',
    text: 'Does the device enter the body through a body orifice?',
    description: 'Consider natural body openings such as mouth, nose, ears, eyes, or other natural openings.',
    options: [
      {
        id: 'yes',
        text: 'Yes, enters through body orifice',
        nextQuestionId: 'orifice_depth'
      },
      {
        id: 'no',
        text: 'No, does not enter body',
        nextQuestionId: 'duration_contact'
      }
    ]
  },

  orifice_depth: {
    id: 'orifice_depth',
    text: 'Does the device penetrate beyond the pharynx, external auditory canal, or nasal cavity?',
    description: 'Consider if the device goes deeper into the body beyond these initial entry points.',
    options: [
      {
        id: 'yes',
        text: 'Yes, penetrates beyond these areas',
        nextQuestionId: 'orifice_duration'
      },
      {
        id: 'no',
        text: 'No, remains in these areas',
        result: {
          class: 'Class I',
          rule: 'Canada Rule 2',
          description: 'Non-invasive devices or devices that do not penetrate beyond the pharynx, external auditory canal, or nasal cavity are Class I.'
        }
      }
    ]
  },

  orifice_duration: {
    id: 'orifice_duration',
    text: 'What is the intended duration of contact?',
    description: 'Consider how long the device is intended to remain in the body.',
    options: [
      {
        id: 'short_term',
        text: 'Short term (≤ 30 days)',
        result: {
          class: 'Class II',
          rule: 'Canada Rule 4',
          description: 'Invasive devices through body orifices with short-term contact are Class II.'
        }
      },
      {
        id: 'long_term',
        text: 'Long term (> 30 days)',
        result: {
          class: 'Class III',
          rule: 'Canada Rule 5',
          description: 'Invasive devices through body orifices with long-term contact are Class III.'
        }
      }
    ]
  },

  duration_contact: {
    id: 'duration_contact',
    text: 'What is the duration of contact with the patient?',
    description: 'Consider how long the device is intended to be in contact with the patient during normal use.',
    options: [
      {
        id: 'transient',
        text: 'Transient use (≤ 60 minutes)',
        nextQuestionId: 'active_device'
      },
      {
        id: 'short_term',
        text: 'Short term (> 60 minutes to 30 days)',
        nextQuestionId: 'active_device'
      },
      {
        id: 'long_term',
        text: 'Long term (> 30 days)',
        nextQuestionId: 'active_device'
      }
    ]
  },

  active_device: {
    id: 'active_device',
    text: 'Is this an active device?',
    description: 'An active device relies on a source of energy other than that directly generated by the human body or gravity.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active device',
        nextQuestionId: 'active_therapeutic'
      },
      {
        id: 'no',
        text: 'No, non-active device',
        result: {
          class: 'Class I',
          rule: 'Canada Rule 1',
          description: 'Non-active, non-invasive devices are Class I.'
        }
      }
    ]
  },

  active_therapeutic: {
    id: 'active_therapeutic',
    text: 'Is this an active therapeutic device?',
    description: 'An active therapeutic device is intended to deliver or exchange energy, substances or other elements to or with the patient.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active therapeutic device',
        nextQuestionId: 'potentially_hazardous'
      },
      {
        id: 'no',
        text: 'No, active diagnostic device',
        result: {
          class: 'Class II',
          rule: 'Canada Rule 9',
          description: 'Active diagnostic devices are generally Class II.'
        }
      }
    ]
  },

  potentially_hazardous: {
    id: 'potentially_hazardous',
    text: 'Is the device intended to administer energy or substances in a potentially hazardous way?',
    description: 'Consider if the nature or method of energy/substance delivery could present a risk to the patient.',
    options: [
      {
        id: 'yes',
        text: 'Yes, potentially hazardous',
        result: {
          class: 'Class III',
          rule: 'Canada Rule 10',
          description: 'Active therapeutic devices that administer energy or substances in a potentially hazardous way are Class III.'
        }
      },
      {
        id: 'no',
        text: 'No, not potentially hazardous',
        result: {
          class: 'Class II',
          rule: 'Canada Rule 9',
          description: 'Active therapeutic devices that are not potentially hazardous are Class II.'
        }
      }
    ]
  }
};
