export interface MDRRule {
  id: string;
  title: string;
  text: string;
  source: string;
}

export const mdrRuleTexts: Record<string, MDRRule> = {
  'rule_1': {
    id: 'rule_1',
    title: 'Rule 1',
    text: 'All non-invasive devices are in Class I, unless one of the rules set out hereinafter applies.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 1'
  },
  'rule_5': {
    id: 'rule_5',
    title: 'Rule 5',
    text: 'All invasive devices with respect to body orifices, other than surgically invasive devices, which are not intended for connection to an active medical device or which are intended for short-term use, are in Class I.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 5'
  },
  'rule_6': {
    id: 'rule_6',
    title: 'Rule 6',
    text: 'All surgically invasive devices intended for short-term use are in Class IIa unless they are: (a) intended specifically to control, diagnose, monitor or correct a defect of the heart or the central circulatory system through direct contact with those parts of the body, in which case they are in Class III; (b) active therapeutic devices intended for direct contact with vital organs, in which case they are in Class III; (c) intended specifically for use in direct contact with the central nervous system, in which case they are in Class III; (d) intended to supply energy in the form of ionizing radiation in which case they are in Class IIb; (e) intended to have a biological effect or to be absorbed wholly or largely by the human body, in which case they are in Class III; or (f) intended to administer medicinal products by means of a delivery system, if this is done in a manner that is potentially hazardous taking account of the mode of application, in which case they are in Class IIb.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 6'
  },
  'rule_8': {
    id: 'rule_8',
    title: 'Rule 8',
    text: 'All implantable devices and long-term surgically invasive devices are in Class IIb unless they are intended: (a) to be placed in the teeth, in which case they are in Class IIa; (b) to be used in direct contact with the heart, the central circulatory system or the central nervous system, in which case they are in Class III; (c) to have a biological effect or to be absorbed wholly or largely by the human body, in which case they are in Class III; (d) to undergo chemical change in the body except if the devices are placed in the teeth, in which case they are in Class III; or (e) to administer medicinal products, in which case they are in Class III.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 8'
  },
  'rule_14': {
    id: 'rule_14',
    title: 'Rule 14',
    text: 'All devices incorporating, as an integral part, a substance which, if used separately, can be considered to be a medicinal product as defined in Article 1 of Directive 2001/83/EC and which is liable to act on the human body with action ancillary to that of the devices, are in Class III.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 14'
  },
  'rule_15': {
    id: 'rule_15',
    title: 'Rule 15',
    text: 'All devices used for contraception or the prevention of the transmission of sexually transmitted diseases are in Class IIb, unless they are implantable or long-term invasive devices, in which case they are in Class III.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 15'
  },
  'rule_16': {
    id: 'rule_16',
    title: 'Rule 16',
    text: 'All devices intended specifically to be used for disinfecting, cleaning, rinsing or, when appropriate, hydrating contact lenses are in Class IIb. All devices intended specifically to be used for disinfecting medical devices are in Class IIa, unless they are disinfecting solutions or washer-disinfectors intended specifically to be used for disinfecting invasive devices as the end point of processing, in which case they are in Class IIb.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 16'
  },
  'rule_17': {
    id: 'rule_17',
    title: 'Rule 17',
    text: 'Devices specifically intended for recording of diagnostic images generated by X-ray radiation are in Class IIa.',
    source: 'EU MDR 2017/745 - Annex VIII, Rule 17'
  }
};

export const getRuleText = (ruleId: string): MDRRule | null => {
  return mdrRuleTexts[ruleId] || null;
};

export const getRuleByNumber = (ruleNumber: number | string): MDRRule | null => {
  const ruleId = `rule_${ruleNumber}`;
  return getRuleText(ruleId);
};