import { Question, ClassificationResult } from '@/types/classification';

// UK MHRA Medical Device Classification Rules
// Based on UK MDR 2002 (as amended) - Follows EU MDR principles with UK-specific modifications

export const ukClassificationQuestions: Record<string, Question> = {
  initial: {
    id: 'initial',
    text: 'Is this product a medical device?',
    description: 'A medical device is defined as any instrument, apparatus, appliance, software, implant, reagent, material or other article intended by the manufacturer for use in human beings for medical purposes.',
    options: [
      {
        id: 'yes',
        text: 'Yes, this is a medical device',
        nextQuestionId: 'principal_mode_of_action'
      },
      {
        id: 'no',
        text: 'No, this is not a medical device',
        result: {
          class: 'Not a medical device',
          rule: 'UK MDR 2002',
          description: 'Product does not meet the definition of a medical device under UK regulations.'
        }
      }
    ]
  },

  principal_mode_of_action: {
    id: 'principal_mode_of_action',
    text: 'Does the product achieve its principal intended action by pharmacological, immunological, or metabolic means?',
    description: 'Medical devices typically achieve their principal action by other means (e.g., physical, mechanical, software-driven). They can be assisted by pharmacological, immunological, or metabolic means, but these should not be the principal mode of action.',
    options: [
      {
        id: 'yes_pharma',
        text: 'Yes, its principal action is through these means',
        result: {
          class: 'Consultation required',
          rule: 'UK MDR 2002',
          description: 'Product may not be a medical device if its principal intended action is pharmacological, immunological, or metabolic. Consultation with MHRA advised.'
        }
      },
      {
        id: 'no_other',
        text: 'No, its principal action is by other means',
        nextQuestionId: 'invasiveness'
      }
    ]
  },

  invasiveness: {
    id: 'invasiveness',
    text: 'Is the device invasive?',
    description: 'An invasive device partially or wholly penetrates the body, either through a body orifice or through the surface of the body.',
    options: [
      {
        id: 'non_invasive',
        text: 'Non-invasive',
        nextQuestionId: 'active_device'
      },
      {
        id: 'invasive',
        text: 'Invasive',
        nextQuestionId: 'surgically_invasive'
      }
    ]
  },

  surgically_invasive: {
    id: 'surgically_invasive',
    text: 'Is the device surgically invasive?',
    description: 'A surgically invasive device penetrates the body through the surface with the aid or in the context of a surgical operation.',
    options: [
      {
        id: 'yes',
        text: 'Yes, surgically invasive',
        nextQuestionId: 'implantable'
      },
      {
        id: 'no',
        text: 'No, not surgically invasive',
        nextQuestionId: 'body_orifice'
      }
    ]
  },

  implantable: {
    id: 'implantable',
    text: 'Is the device implantable?',
    description: 'An implantable device is intended to be totally or partially introduced into the human body or to replace an epithelial surface through clinical intervention and remain in place after the procedure.',
    options: [
      {
        id: 'yes',
        text: 'Yes, implantable',
        nextQuestionId: 'active_implantable'
      },
      {
        id: 'no',
        text: 'No, not implantable',
        nextQuestionId: 'cardiovascular_system'
      }
    ]
  },

  active_implantable: {
    id: 'active_implantable',
    text: 'Is this an active implantable device?',
    description: 'An active implantable device relies on a source of energy other than that directly generated by the human body or gravity.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active implantable',
        result: {
          class: 'Class III',
          rule: 'UK MDR Schedule 1, Rule 9',
          description: 'All active implantable medical devices are classified as Class III.'
        }
      },
      {
        id: 'no',
        text: 'No, not active implantable',
        nextQuestionId: 'cardiovascular_system'
      }
    ]
  },

  cardiovascular_system: {
    id: 'cardiovascular_system',
    text: 'Does the device come into contact with the cardiovascular system?',
    description: 'Consider if the device is intended to be used in direct contact with the heart or central circulatory system.',
    options: [
      {
        id: 'yes',
        text: 'Yes, contacts cardiovascular system',
        result: {
          class: 'Class III',
          rule: 'UK MDR Schedule 1, Rule 6',
          description: 'Surgically invasive devices intended for contact with the cardiovascular system are Class III.'
        }
      },
      {
        id: 'no',
        text: 'No, does not contact cardiovascular system',
        nextQuestionId: 'central_nervous_system'
      }
    ]
  },

  central_nervous_system: {
    id: 'central_nervous_system',
    text: 'Does the device come into contact with the central nervous system?',
    description: 'Consider if the device is intended to be used in direct contact with the brain, spinal cord, or meninges.',
    options: [
      {
        id: 'yes',
        text: 'Yes, contacts central nervous system',
        result: {
          class: 'Class III',
          rule: 'UK MDR Schedule 1, Rule 6',
          description: 'Surgically invasive devices intended for contact with the central nervous system are Class III.'
        }
      },
      {
        id: 'no',
        text: 'No, does not contact central nervous system',
        nextQuestionId: 'reusable_surgical'
      }
    ]
  },

  reusable_surgical: {
    id: 'reusable_surgical',
    text: 'Is this a reusable surgical instrument?',
    description: 'Reusable surgical instruments are intended for surgical purposes to cut, drill, saw, scratch, scrape, clamp, retract, clip or perform similar procedures, without connection to any active device.',
    options: [
      {
        id: 'yes',
        text: 'Yes, reusable surgical instrument',
        result: {
          class: 'Class I',
          rule: 'UK MDR Schedule 1, Rule 3',
          description: 'Reusable surgical instruments are Class I with special requirements for reprocessing.'
        }
      },
      {
        id: 'no',
        text: 'No, not a reusable surgical instrument',
        result: {
          class: 'Class IIa',
          rule: 'UK MDR Schedule 1, Rule 5',
          description: 'Surgically invasive devices for transient or short-term use are generally Class IIa.'
        }
      }
    ]
  },

  body_orifice: {
    id: 'body_orifice',
    text: 'Does the device enter the body through a body orifice?',
    description: 'Consider natural body openings such as mouth, nose, ears, eyes, or other natural openings.',
    options: [
      {
        id: 'yes',
        text: 'Yes, enters through body orifice',
        nextQuestionId: 'pharynx_ear_canal'
      },
      {
        id: 'no',
        text: 'No, does not enter body orifice',
        result: {
          class: 'Class I',
          rule: 'UK MDR Schedule 1, Rule 1',
          description: 'Non-invasive devices are generally Class I.'
        }
      }
    ]
  },

  pharynx_ear_canal: {
    id: 'pharynx_ear_canal',
    text: 'Does the device go beyond the pharynx, ear canal, or nasal cavity?',
    description: 'Consider if the device penetrates deeper into the body beyond these initial entry points.',
    options: [
      {
        id: 'yes',
        text: 'Yes, goes beyond these areas',
        result: {
          class: 'Class IIa',
          rule: 'UK MDR Schedule 1, Rule 4',
          description: 'Invasive devices with respect to body orifices that go beyond the pharynx, ear canal, or nasal cavity are Class IIa.'
        }
      },
      {
        id: 'no',
        text: 'No, remains in these areas',
        result: {
          class: 'Class I',
          rule: 'UK MDR Schedule 1, Rule 1',
          description: 'Invasive devices through body orifices that remain in pharynx, ear canal, or nasal cavity are Class I.'
        }
      }
    ]
  },

  active_device: {
    id: 'active_device',
    text: 'Is this an active device?',
    description: 'An active device relies on a source of energy other than that directly generated by the human body or gravity.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active device',
        nextQuestionId: 'therapeutic_active'
      },
      {
        id: 'no',
        text: 'No, non-active device',
        result: {
          class: 'Class I',
          rule: 'UK MDR Schedule 1, Rule 1',
          description: 'Non-active, non-invasive devices are Class I.'
        }
      }
    ]
  },

  therapeutic_active: {
    id: 'therapeutic_active',
    text: 'Is this an active therapeutic device?',
    description: 'An active therapeutic device is intended to administer or exchange energy, substances or other elements between the device and the patient.',
    options: [
      {
        id: 'yes',
        text: 'Yes, active therapeutic device',
        result: {
          class: 'Class IIa',
          rule: 'UK MDR Schedule 1, Rule 10',
          description: 'Active therapeutic devices intended to administer or exchange energy are generally Class IIa.'
        }
      },
      {
        id: 'no',
        text: 'No, active diagnostic device',
        nextQuestionId: 'ionizing_radiation'
      }
    ]
  },

  ionizing_radiation: {
    id: 'ionizing_radiation',
    text: 'Does the device emit ionizing radiation?',
    description: 'Consider if the device produces X-rays, gamma rays, or other forms of ionizing radiation.',
    options: [
      {
        id: 'yes',
        text: 'Yes, emits ionizing radiation',
        result: {
          class: 'Class IIb',
          rule: 'UK MDR Schedule 1, Rule 11',
          description: 'Active devices intended to emit ionizing radiation for diagnostic purposes are Class IIb.'
        }
      },
      {
        id: 'no',
        text: 'No, does not emit ionizing radiation',
        result: {
          class: 'Class IIa',
          rule: 'UK MDR Schedule 1, Rule 10',
          description: 'Active diagnostic devices are generally Class IIa.'
        }
      }
    ]
  }
};
